In [23]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable 
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from torchvision import datasets, transforms
# from PIL import Image

In [24]:
BATCH_SIZE=32 #大概需要2G的显存
EPOCHS=5
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [25]:
def left_top(x):
    nsam = x.shape[0]
    nrow = x.shape[1]
    ncol = x.shape[2]
    z = np.zeros((nsam, nrow, ncol), dtype=np.double)
    data1 = np.concatenate((x, z), axis=1)
    data2 = np.concatenate((z, z), axis=1)
    data3 = np.concatenate((data1, data2), 2)
    return data3
def right_bottom(x):
    nsam = x.shape[0]
    nrow = x.shape[1]
    ncol = x.shape[2]
    z = np.zeros((nsam, nrow, ncol), dtype=np.double)
    data1 = np.concatenate((z, z), axis=1)
    data2 = np.concatenate((z, x), axis=1)
    data3 = np.concatenate((data1, data2), 2)
    return data3

In [26]:
def getType(dataset,x):
    index = np.where(dataset[:, 0] == x)
    for i in index:
        Type = dataset[i]
    return Type

In [27]:
def getPixel(x):
    pixel = x[:, 1:]
    return pixel
def getLabel(x):
    label = x[:, 0]
    return label

In [28]:
class train(Dataset):
    def __init__(self):
        
        mnist_train = pd.read_csv('mnist_train.csv')
        train = mnist_train.values

        mnist_train_0=getType(train,0)
        mnist_train_1=getType(train,1)   
        mnist_train_2=getType(train,2)
        mnist_train_3=getType(train,3)   
        
            
        nrow = 28
        ncol = 28

        # X and label
        x1 = getPixel(mnist_train_1)
        x0 =getPixel(mnist_train_0)
        y1 = getLabel(mnist_train_1)
        y0 = getLabel(mnist_train_0)
        x2 = getPixel(mnist_train_2)
        x3 =getPixel(mnist_train_3)
        y2= getLabel(mnist_train_2)
        y3 = getLabel(mnist_train_3)

        # X reshape to 28 28
               
        nx1 = x1.shape[0]
        nx0 = x0.shape[0]
        nx2 = x2.shape[0]
        nx3 = x3.shape[0]
       
        x0_reshape = x0.reshape((nx0, nrow, ncol))
        x1_reshape = x1.reshape((nx1, nrow, ncol))
        x2_reshape = x2.reshape((nx2, nrow, ncol))
        x3_reshape = x3.reshape((nx3, nrow, ncol))


        left0 = left_top(x0_reshape)
        right1 = right_bottom(x1_reshape)
        
        left2=left_top(x2_reshape)
        right3=right_bottom(x3_reshape)
        
        
        
        train_data1 = np.concatenate((left0, right1), axis=0)
        train_data2 = np.concatenate((left2, right3), axis=0)
        train_data= np.concatenate((train_data1, train_data2), axis=0)
        
        nn = train_data.shape[0]

        # reshape to 3136 which is 56*56
        train_data_reshape = train_data
        train_data_reshape = torch.from_numpy(train_data_reshape)
        train_data_reshape = torch.unsqueeze(train_data_reshape, 1)
        
        yy1 = np.concatenate((y0, y1), axis=0)
        yy2=np.concatenate((y2, y3), axis=0)
        yy=np.concatenate((yy1, yy2), axis=0)
        
        yy=torch.from_numpy(yy)
      
        self.len = yy.shape[0]

        self.x_data = train_data_reshape

        self.y_data = yy


    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]
      

    def __len__(self):
        return self.len
dataset1= train()
train_loader = DataLoader(dataset=dataset1,
                          batch_size=32,
                          shuffle=True,
                          num_workers=2)

In [29]:
class test(Dataset):
    def __init__(self):
  
        mnist_test = pd.read_csv('mnist_test.csv')
        testtest= mnist_test.values
        
        
        test0=getType(testtest,0)
        test1=getType(testtest,1)
        test2=getType(testtest,2)
        test3=getType(testtest,3)
        nrow = 28
        ncol = 28

        # X and label
        x1 = getPixel(test1)
        x0 =getPixel(test0)
        y1 = getLabel(test1)
        y0 = getLabel(test0)
        x2 = getPixel(test2)
        x3 =getPixel(test3)
        y2 = getLabel(test2)
        y3 = getLabel(test3)



        # X reshape to 28 28
        nx1 = x1.shape[0]
        nx0 = x0.shape[0]
        nx2 = x2.shape[0]
        nx3 = x3.shape[0]
      
        x0_reshape = x0.reshape((nx0, nrow, ncol))
        x1_reshape = x1.reshape((nx1, nrow, ncol))
        x2_reshape = x2.reshape((nx2, nrow, ncol))
        x3_reshape = x3.reshape((nx3, nrow, ncol))


        left0 = left_top(x0_reshape)
        right1 = right_bottom(x1_reshape)
        
        left2=left_top(x2_reshape)
        right3=right_bottom(x3_reshape)
        
        
        
        train_data1 = np.concatenate((left0, right1), axis=0)
        train_data2 = np.concatenate((left2, right3), axis=0)
        train_data= np.concatenate((train_data1, train_data2), axis=0)

        

        nn = train_data.shape[0]

        
        train_data_reshape = train_data
        train_data_reshape = torch.from_numpy(train_data_reshape)
        train_data_reshape = torch.unsqueeze(train_data_reshape, 1)
        
        yy1 = np.concatenate((y0, y1), axis=0)
        yy2=np.concatenate((y2, y3), axis=0)
        yy=np.concatenate((yy1, yy2), axis=0)
        
        yy=torch.from_numpy(yy)
      
        self.len = yy.shape[0]

        self.x_data = train_data_reshape

        self.y_data = yy


    def __getitem__(self, index):
        # img = Image.fromarray(self.x_data[index])
        return self.x_data[index], self.y_data[index]

    def __len__(self):
        return self.len
dataset2 = test()
test_loader = DataLoader(dataset=dataset2,
                          batch_size=32,
                          shuffle=True,
                          num_workers=2)

In [30]:
class ConvNet(nn.Module):
    def __init__(self):
        super().__init__()
        # 1,28x28
        self.conv1=nn.Conv2d(1,10,5) # 10, 24x24
        self.conv2=nn.Conv2d(10,20,3) # 128, 10x10
        self.fc1 = nn.Linear(2880,300)
        self.fc2 = nn.Linear(300,4)
    def forward(self,x):
        in_size = x.size(0)
        out = self.conv1(x) #24
        out = F.relu(out)
        out = F.max_pool2d(out, 2, 2)  #12
        out = self.conv2(out) #10
        out = F.relu(out)
        out = F.max_pool2d(out, 2, 2)  #12
        out = F.relu(out)   
        out = out.view(in_size,-1)
        out = self.fc1(out)
        out = F.relu(out)
        out = self.fc2(out)
        # out = F.log_softmax(out,dim=1)
        # out = F.softmax(out,dim=1)
        return out

In [31]:
model = ConvNet()
model = model.to(DEVICE)
model= model.double()
optimizer = optim.Adam(model.parameters())
# criterion = nn.CrossEntropyLoss()

In [32]:
def train(model, device, train_loader, optimizer, epoch):
    model.train()

    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        # print(data.size(), target.size())
        optimizer.zero_grad()
        output=model(data)
        # print(output)
        #print(target)
        # loss = F.nll_loss(output, target)
        # print(loss)
        loss = F.cross_entropy(output, target)
        loss.backward()
        optimizer.step()
        if(batch_idx+1)%100 == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))

def test(model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data.double())
            print(output)
            print(target)
            test_loss += F.cross_entropy(output, target, reduction='sum').item() # 将一批的损失相加
            pred = output.max(1, keepdim=True)[1] # 找到概率最大的下标
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.4f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))






In [33]:
for epoch in range(1, EPOCHS + 1):
    train(model, DEVICE, train_loader, optimizer, epoch)
    test(model, DEVICE, test_loader)

Train Epoch: 1 [3168/24754 (13%)]	Loss: 0.021714
Train Epoch: 1 [6368/24754 (26%)]	Loss: 0.025134
Train Epoch: 1 [9568/24754 (39%)]	Loss: 0.000024
Train Epoch: 1 [12768/24754 (52%)]	Loss: 0.000808
Train Epoch: 1 [15968/24754 (64%)]	Loss: 0.000047
Train Epoch: 1 [19168/24754 (77%)]	Loss: 0.000172
Train Epoch: 1 [22368/24754 (90%)]	Loss: 0.000075
tensor([[ 22.1139, -22.3416,   9.0875,  -3.1564],
        [ 25.4190, -24.9409,   9.1895,  -3.7588],
        [ -3.1863,  15.3647,  -7.8207,  -6.1470],
        [ -5.1176,  20.9034, -10.9093, -11.5429],
        [  5.4475, -16.8374,  17.1707,  -3.1084],
        [ -3.7658,  -1.8075, -11.6622,  13.2228],
        [  3.7754, -17.7166,  19.2881,  -1.8761],
        [ -3.9152,  17.1528,  -9.8871,  -8.7443],
        [ 20.5529, -20.8222,   6.8376,  -3.0793],
        [ 18.4664, -23.1329,  11.4993,  -2.9734],
        [  7.5239, -19.0526,  19.4399,  -2.6597],
        [ -4.2275,  16.4318, -10.5813,  -7.9034],
        [  5.6987, -18.7530,  20.1028,  -2.2700],
   

tensor([[ 23.2867, -26.3033,   9.6432,  -3.4413],
        [ -7.4476,  -0.4325, -16.1747,  17.2960],
        [ 22.3138, -22.7094,   8.1135,  -2.8538],
        [  1.6732, -22.9356,  26.9623,  -2.5629],
        [ -3.1470, -21.0949,  26.7916,  -2.7542],
        [ -6.9100,  -2.3334, -17.2600,  19.7517],
        [ 21.1016, -23.5460,  10.3491,  -3.7033],
        [  0.9794, -19.9717,  23.9112,  -3.2910],
        [ 24.4507, -24.7670,   7.4408,  -2.9253],
        [ -0.7932, -21.0851,  24.9003,  -3.0082],
        [ 20.0973, -21.8724,   9.2133,  -3.2047],
        [ -6.5730,  -0.4999, -13.6726,  16.1668],
        [  7.0805, -20.4819,  20.8756,  -2.8679],
        [ -5.0339,  15.3570, -11.7374,  -5.1439],
        [ -6.3039,  -0.4380, -15.4538,  16.7056],
        [ 24.1374, -25.1157,  10.7182,  -3.8104],
        [ 15.9717, -19.6113,  10.5192,  -3.9649],
        [ -4.6782,  15.3461, -11.6323,  -5.8108],
        [ 23.0203, -25.0873,   8.0429,  -4.0322],
        [ -0.4879, -21.1447,  25.8779,  -3.1189],


tensor([[ -2.0673,   7.6088,  -5.7415,  -1.4303],
        [ 23.4709, -23.0545,   9.8558,  -3.6881],
        [ 24.0450, -26.1481,   9.1402,  -4.4052],
        [ 20.0765, -22.5289,  10.5987,  -2.5877],
        [  1.7040, -15.7591,  19.5804,  -2.7144],
        [ -5.5192,  -0.6412, -14.1640,  14.0557],
        [ 21.2281, -22.3572,   9.5029,  -3.1562],
        [ -4.4260,  19.0976, -10.1307,  -8.8050],
        [ -0.3309, -21.2490,  24.8228,  -4.3503],
        [ 22.3135, -23.8342,   8.4767,  -3.3243],
        [  2.2263, -14.8088,  17.5302,  -3.4967],
        [ 21.2430, -24.1518,  10.3773,  -3.3263],
        [ -2.1605, -18.0662,  22.7240,  -3.3929],
        [ -4.6764,  14.4194, -10.2694,  -4.7932],
        [ -5.1974,   2.2674, -13.2221,  10.6940],
        [ 23.9771, -22.3518,   9.4715,  -3.4608],
        [ 23.8972, -23.7173,   9.2007,  -4.1873],
        [  4.3195, -17.1531,  18.3830,  -3.0125],
        [  2.0444, -15.9280,  19.6315,  -1.6089],
        [ -6.1360,   0.0534, -15.3393,  16.0782],


tensor([[ -4.0195,   9.7960,  -8.2129,  -2.7024],
        [ -6.4035,   2.0428, -13.2046,  10.8315],
        [ -6.6414,  -0.6730, -14.7226,  15.7805],
        [  3.0223, -20.4927,  24.6684,  -4.9725],
        [  1.8280, -18.9146,  21.1924,  -2.1294],
        [ 23.2287, -23.6771,  10.9502,  -2.9283],
        [ 19.4021, -22.3038,   9.1995,  -3.2250],
        [ -5.7571,  -0.1473, -13.7263,  13.4755],
        [ 20.9408, -26.0289,  13.7724,  -3.2185],
        [ -3.7183,  18.5428, -10.1572,  -7.4595],
        [ -3.5851,  14.8663,  -9.5895,  -5.5601],
        [ -0.4902, -18.0276,  22.2331,  -2.0930],
        [ -3.7394,  17.8988, -10.7617,  -8.1174],
        [ -3.7352,  16.1319,  -9.8971,  -7.5009],
        [ -4.0871,  16.9483, -11.2106,  -6.1255],
        [ -1.0076, -22.1264,  27.0387,  -2.1253],
        [ -4.7605,   3.6206, -13.8290,   8.8462],
        [  0.2909, -18.0586,  21.8367,  -4.0063],
        [ 20.5675, -21.4254,   9.6609,  -3.3836],
        [ -4.4498,  -2.8344, -13.9832,  18.0171],


tensor([[-7.2733e+00,  1.0882e+00, -1.8504e+01,  1.8330e+01],
        [-5.7441e+00,  3.0023e+00, -1.3661e+01,  9.8669e+00],
        [ 9.5197e-01, -2.0040e+01,  2.4320e+01, -2.9046e+00],
        [ 1.9761e+01, -2.0883e+01,  1.0969e+01, -3.5505e+00],
        [-6.9296e+00,  8.3003e-01, -1.5952e+01,  1.7027e+01],
        [-4.6475e+00,  1.5071e+01, -9.6755e+00, -5.7652e+00],
        [ 1.3840e+01, -1.7886e+01,  1.0306e+01, -3.3477e+00],
        [ 2.1976e+01, -2.4842e+01,  9.0302e+00, -3.9243e+00],
        [ 1.2519e+00, -1.1374e+01,  1.3737e+01, -1.5004e+00],
        [ 3.9247e+00, -2.2253e+01,  2.6442e+01, -1.8784e+00],
        [ 1.6522e+00, -1.4645e+01,  1.7379e+01, -2.9256e+00],
        [ 3.2938e+00, -1.8402e+01,  2.1333e+01, -2.8637e+00],
        [-3.4590e+00,  1.3276e+01, -8.8757e+00, -5.1864e+00],
        [ 6.1020e+00, -1.7712e+01,  1.6701e+01, -2.5493e+00],
        [-3.5187e-02, -1.2716e+01,  1.4232e+01, -3.4139e+00],
        [-5.5268e+00,  8.1849e-01, -1.4208e+01,  1.2411e+01],
        

tensor([[ 22.6915, -25.5362,  11.8693,  -2.7032],
        [ -8.5626,   0.0771, -16.5804,  16.9555],
        [ -4.8106,  14.8178,  -9.3893,  -6.8556],
        [ -6.0863,   8.5103, -12.0221,   0.3021],
        [ -3.9118,  20.0012, -11.6796,  -7.8866],
        [ -5.6689,  -1.5830, -14.3674,  15.9432],
        [ 20.7386, -21.0638,   9.9179,  -4.0000],
        [ -3.8074,  20.2376, -11.0986,  -8.6217],
        [  3.6792, -17.8884,  20.1194,  -2.8228],
        [ -3.9313,  13.4437, -10.1492,  -6.9612],
        [ -3.1419,  17.6171,  -9.6384,  -7.3824],
        [  0.8609, -16.5501,  20.0756,  -3.6148],
        [ -0.5274, -17.1597,  21.3049,  -3.1895],
        [ 16.7988, -22.3916,  10.6656,  -3.6870],
        [ 24.2007, -22.3214,   8.1940,  -2.7215],
        [  6.3425, -20.3519,  21.4011,  -3.8887],
        [  1.1285, -21.6745,  26.1855,  -1.8647],
        [ -6.3593,   2.2279, -16.0685,  14.1414],
        [ 21.3019, -23.3433,   8.4940,  -3.6598],
        [ 20.2818, -22.3988,   8.4841,  -3.9122],


tensor([[ -4.2292,  14.4779, -10.0433,  -5.2220],
        [ -6.6624,   0.3784, -15.9126,  17.2531],
        [ -3.4437,   2.7893, -13.9672,   9.6914],
        [ -4.3385,  13.7005, -10.9432,  -7.6212],
        [ -3.3853,  19.5497,  -9.5637,  -9.9710],
        [ -1.7887, -23.3852,  27.5733,  -4.0834],
        [ -5.4202,  18.2691, -11.9766,  -7.3017],
        [ -5.4764,  -2.0678, -12.6558,  15.5969],
        [ 19.9464, -21.5624,  10.5753,  -3.1121],
        [ -6.0840,  -2.6053, -14.3699,  17.2545],
        [ -6.6716,   0.8096, -16.6237,  15.8333],
        [ -4.2691,  14.5412,  -9.2592,  -6.5411],
        [ -3.0961,  13.1417,  -6.9281,  -7.0690],
        [ 21.4760, -23.3046,   9.0644,  -3.2418],
        [  2.9640, -20.1340,  23.6924,  -2.7427],
        [ -3.6201,  12.6592,  -8.4072,  -6.9542],
        [ 22.2298, -24.8470,   9.7774,  -3.3999],
        [ 16.7169, -21.3781,  10.3158,  -3.4017],
        [  2.3231, -20.3965,  23.4133,  -2.8320],
        [ 19.6113, -22.4251,  13.2279,  -3.8272],


tensor([[  6.0228, -21.4376,  22.2578,  -3.4044],
        [ -5.6413,   0.6456, -14.8193,  15.2920],
        [ 19.1211, -19.4995,   9.9647,  -3.9196],
        [ -3.7642,  16.5602, -10.6584,  -6.3476],
        [ 20.0903, -21.5296,  10.2480,  -2.7640],
        [ -3.8727,  17.3260, -11.1432,  -7.0285],
        [  4.2783, -19.7830,  22.8888,  -2.1136],
        [ 23.1408, -24.9732,   8.3749,  -3.8560],
        [ 20.4998, -21.4767,   9.9044,  -2.9347],
        [ -6.8102,  -1.2728, -15.4743,  17.0158],
        [ -7.6016,  -1.2241, -14.7464,  17.2216],
        [ -4.1000,   0.7447, -13.7201,  12.8437],
        [ -2.6206,  -0.0822,  -8.6397,   9.0062],
        [ 15.7192, -20.0437,  10.7268,  -3.1826],
        [  0.0728, -21.3468,  25.2601,  -2.4452],
        [  0.2112, -15.9101,  18.9336,  -2.8595],
        [ -4.8169,  -1.4981, -14.8483,  17.2328],
        [ -4.0643,  18.3630, -10.4225,  -8.9039],
        [ -6.5357,  -2.6773, -15.0389,  18.9393],
        [ -5.7190,  -3.1528, -14.5268,  16.9383],


tensor([[ -0.4102, -17.4165,  22.4358,  -3.4871],
        [ -3.7669,  18.1282, -11.7856,  -6.4380],
        [ 26.2348, -26.4602,   7.6837,  -3.9124],
        [ -3.9919,  18.2909, -10.5118,  -7.8207],
        [ 23.7059, -23.7499,   8.7541,  -3.0664],
        [ -6.4233,   3.0983, -14.5680,  11.7447],
        [ -3.6264,  14.2779,  -9.3123,  -6.7262],
        [  2.3694, -19.5382,  22.1403,  -3.2745],
        [  0.5604, -18.5253,  23.3707,  -2.5665],
        [ -4.3587,  13.6902,  -9.4546,  -6.2941],
        [ -4.1203,  18.7651,  -9.6193,  -9.1485],
        [ -6.4219,   0.2165, -16.4785,  17.5457],
        [ -4.5467,  15.6755, -10.2419,  -7.0127],
        [ 19.9987, -23.3625,  11.4629,  -3.7065],
        [ 26.0535, -24.0124,   5.9288,  -2.6904],
        [ 23.9818, -24.7048,   9.9560,  -3.2049],
        [ -1.8786, -22.1356,  26.0556,  -3.6307],
        [ 18.3850, -20.8039,   8.3114,  -3.5189],
        [ 19.7278, -23.8422,  11.3352,  -3.2321],
        [ -6.0131,  -2.3595, -14.8158,  17.2313],


tensor([[ -6.3661,  -1.1823, -17.3004,  19.4436],
        [ -6.3190,  -1.8818, -15.2278,  17.3620],
        [ -3.9066,  12.7805,  -9.2101,  -4.6553],
        [ -8.1563,  -2.1137, -18.9073,  23.0091],
        [ 20.3928, -19.5520,   7.7250,  -3.6525],
        [ -7.9746,  -1.8301, -15.4200,  18.2479],
        [  5.8478, -14.5026,  13.9083,  -2.6868],
        [ -7.6531,  -0.0888, -16.5225,  17.3817],
        [ -7.2595,   0.8469, -16.0106,  16.1469],
        [  2.2932, -21.5932,  25.4709,  -3.7084],
        [ 23.6954, -24.3960,  11.4321,  -3.6756],
        [  2.3339, -17.0139,  19.7571,  -2.3659],
        [  1.6705, -20.4653,  24.9658,  -2.3858],
        [ -3.9431,  16.0529,  -9.7242,  -8.2050],
        [ 23.1664, -27.8701,  14.1031,  -3.3494],
        [ 19.0581, -20.3533,   9.2527,  -4.0002],
        [ -7.0006,  -2.2739, -15.4046,  19.0073],
        [ -7.2964,  -4.4137, -17.9983,  23.7269],
        [ -3.9273,  19.7552, -10.3376,  -9.2636],
        [  3.6187, -16.3760,  18.5867,  -1.7873],


tensor([[-3.5058e+00,  1.8333e+01, -1.0719e+01, -7.4594e+00],
        [ 1.4546e+01, -2.0325e+01,  1.0678e+01, -4.2453e+00],
        [-7.0863e+00,  1.6331e+00, -1.4949e+01,  1.3047e+01],
        [-5.7474e+00,  1.9359e+01, -1.2098e+01, -9.5606e+00],
        [ 2.4325e+01, -2.5481e+01,  1.0501e+01, -3.4024e+00],
        [ 5.1648e+00, -1.6071e+01,  1.6690e+01, -3.4223e+00],
        [ 1.4881e+01, -1.9440e+01,  1.1627e+01, -3.9503e+00],
        [-4.0414e+00,  1.2560e+01, -8.5445e+00, -4.7931e+00],
        [ 6.3740e+00, -2.0389e+01,  2.1170e+01, -3.3776e+00],
        [-4.6344e+00,  1.9843e+01, -1.2443e+01, -7.6613e+00],
        [ 1.7715e+01, -2.0907e+01,  1.0674e+01, -4.0978e+00],
        [ 1.8966e+01, -2.0059e+01,  9.1041e+00, -3.0595e+00],
        [ 2.4526e+01, -2.5116e+01,  8.1146e+00, -3.4476e+00],
        [-9.0834e-01, -2.0750e+01,  2.5985e+01, -3.0801e+00],
        [ 1.2049e-02, -2.4123e+01,  2.7276e+01, -4.9013e+00],
        [-3.5406e+00, -2.0289e+01,  2.4962e+01, -3.8370e+00],
        

tensor([3, 3, 1, 0, 1, 3, 1, 3, 3, 3, 0, 3, 0, 2, 2, 0, 1, 1, 2, 2, 1, 0, 3, 1,
        3, 3, 1, 1, 1, 1, 3, 1])
tensor([[ 19.9264, -22.6283,   9.4492,  -3.8218],
        [ -6.6863,  -4.2025, -17.4398,  23.4265],
        [ -4.3617,  19.7383, -10.2800,  -8.9926],
        [ -5.0726,  21.4192, -12.4463,  -9.2480],
        [ -5.4903,   0.9274, -14.2572,  13.6941],
        [ -1.2125, -16.5726,  20.1696,  -2.8017],
        [ -1.0860, -19.0785,  23.5821,  -3.7043],
        [ -8.8054,   3.2121, -16.5919,  12.2600],
        [ 21.0143, -22.9007,   9.5101,  -3.3630],
        [ 20.6516, -24.7222,  12.4640,  -2.8914],
        [ -5.0265,  20.5116, -11.6255,  -9.5905],
        [ -5.1777,  16.1664, -10.9986,  -6.9808],
        [ -6.4179,   0.2121, -14.7347,  13.5266],
        [ -3.6022,  17.6220,  -9.0227,  -8.4678],
        [ -1.2024, -18.9131,  23.9043,  -3.3688],
        [ 23.5633, -24.0348,  10.7908,  -3.8443],
        [ -1.2541, -21.3893,  26.6901,  -1.1299],
        [ 18.4788, -20.9926,  10.5930

tensor([[ -2.2925, -18.0313,  23.2389,  -2.8017],
        [ 19.7300, -21.4562,  11.4395,  -4.2550],
        [ -5.3570,  -0.1276, -14.1039,  15.6914],
        [ 18.1142, -22.9001,  13.4012,  -4.4671],
        [ 21.7571, -23.6424,   8.2951,  -3.9390],
        [ -3.6757, -20.1368,  24.4737,  -3.6081],
        [ -4.4337,  19.2901, -10.6089,  -8.8877],
        [ -6.9619,  -0.8680, -13.8668,  14.4673],
        [ -6.7163,  -0.4229, -15.6861,  17.3686],
        [ -4.0449,  13.4623,  -9.6515,  -3.0792],
        [ -4.0884,  10.5471,  -8.0390,  -4.3785],
        [ -3.8166,  14.1104,  -9.0512,  -6.1700],
        [ -3.6834,  18.0463, -11.7279,  -6.9818],
        [ 19.1248, -21.0962,   9.6878,  -3.9041],
        [ -6.0917,   0.3159, -14.4749,  14.8770],
        [  2.4081, -21.7142,  25.6775,  -2.5674],
        [ -4.6694,  19.7916, -11.1761,  -8.2840],
        [ -3.8911,  17.5628,  -9.4598,  -7.9896],
        [ 18.6256, -22.0681,  10.8953,  -3.4678],
        [ -3.4662,  18.5601,  -9.1267,  -8.2163],


tensor([[ -6.9156,  -0.7412, -15.9422,  17.9997],
        [ -3.3730,  15.9671, -10.0243,  -6.4758],
        [ -6.2053,  -1.9668, -13.7583,  17.3954],
        [ 23.5745, -23.7438,   8.4961,  -3.2776],
        [  3.5639, -21.4338,  23.9066,  -2.6185],
        [ 18.3715, -22.7995,  11.7147,  -2.6486],
        [  1.7839, -19.3967,  23.6146,  -1.2025],
        [ -5.1619,   3.2795, -11.2296,   7.2519],
        [ -5.9369,  -1.7597, -13.6083,  15.4278],
        [ 19.4896, -22.2854,   9.5491,  -3.3832],
        [ -3.8816,  14.5167,  -8.5237,  -7.0704],
        [ -3.5870,  18.7608, -10.4779,  -7.1759],
        [ -5.8741,   1.9317, -15.1111,  13.3949],
        [ -6.0141,   3.2709, -13.7693,   9.0592],
        [ -2.9317,  16.7499, -10.6683,  -5.8057],
        [  1.6791, -17.7941,  21.0192,  -2.7361],
        [ 21.3707, -23.0432,   9.4549,  -2.5730],
        [  4.4939, -19.8096,  20.6714,  -3.1039],
        [ -5.4582,  -1.1186, -12.9068,  13.5088],
        [ -0.5514, -16.4691,  21.5526,  -2.2674],


tensor([[  3.0635, -18.8387,  21.2021,  -3.5701],
        [  0.1824, -18.3077,  20.8581,  -3.5285],
        [ 22.5447, -23.9826,  10.8400,  -3.9077],
        [ -4.6034,  11.8352, -10.2833,  -3.0185],
        [ -5.0944,   9.7955, -12.7364,   0.0510],
        [ -7.7938,   0.1067, -17.1315,  19.3617],
        [ -6.4996,   2.5717, -16.6799,  15.2579],
        [  1.1630, -18.2867,  21.2091,  -3.5636],
        [ -0.1848, -22.2256,  25.8352,  -3.9317],
        [ 20.1115, -20.8834,   7.7524,  -3.4583],
        [  0.2830, -13.8379,  16.4725,  -2.0483],
        [ -3.8023,  17.3401, -10.5958,  -7.9219],
        [ 21.5201, -23.9119,  10.6294,  -3.0825],
        [ -3.8717,  19.5953, -11.1999,  -8.1623],
        [ -4.7024,  17.2169, -11.3017,  -7.4397],
        [ -4.2004,  18.3505, -10.6634,  -7.5552],
        [ -1.2382, -16.7956,  21.6450,  -1.8932],
        [ 23.4384, -25.0379,  12.7482,  -4.4711],
        [ -3.3277,  14.8403, -10.5029,  -4.8324],
        [ -5.4080,  -0.9843, -13.5807,  14.8215],


tensor([[ -5.2724,  -1.8751, -12.3614,  14.6638],
        [ -5.7472,   0.5746, -13.9675,  14.2198],
        [ -4.7271,  21.8211, -11.5454,  -9.4415],
        [ -5.2544,   2.7852, -14.4669,  10.5864],
        [ 22.0027, -23.9313,   8.9602,  -3.8607],
        [ -3.2131, -21.1193,  25.2347,  -2.5557],
        [ -6.0663,   0.6469, -14.5885,  15.6181],
        [ -4.5503,  22.3325, -11.8172,  -9.6905],
        [ -5.7172,   3.2544, -16.0459,  13.5692],
        [ -2.0356, -18.2709,  22.1642,  -3.1708],
        [ -3.5505,  16.8341, -11.8308,  -5.6986],
        [ -7.6723,  -0.5621, -14.0832,  15.5698],
        [ 22.7256, -24.2085,  10.3110,  -3.9519],
        [  1.6248, -19.6499,  24.3347,  -2.9295],
        [ -6.0699,  -1.7405, -12.4734,  12.1361],
        [ -3.9080,  16.3430,  -8.5984,  -8.2742],
        [  6.4440, -14.7760,  13.0280,  -3.4986],
        [ 28.2140, -27.5734,   7.8362,  -4.6148],
        [ -4.3297,  17.7748,  -9.4979,  -8.5437],
        [ -0.2088, -19.6089,  23.7874,  -4.4216],


tensor([[ -6.7590,   0.7600, -16.1716,  14.9878],
        [ -7.0651,  -4.7606, -16.1986,  22.5516],
        [ -5.9914,   2.3204, -12.9555,   9.9974],
        [  2.3990, -20.2231,  23.4140,  -3.9708],
        [  1.3454, -20.8620,  25.2623,  -4.0646],
        [ -5.7670,  -0.2574, -14.3022,  14.8532],
        [ 23.4998, -22.0964,   8.5945,  -3.9752],
        [ 21.8792, -22.1103,   9.0708,  -2.6247],
        [ -4.1172,  15.4818, -11.1558,  -5.9379],
        [  4.7522, -15.8337,  15.6647,  -2.4594],
        [ -6.1768,   3.0663, -14.7511,  11.6392],
        [  3.3833, -18.5184,  20.1632,  -3.3892],
        [ -2.8427,  16.0887,  -7.5810,  -6.9629],
        [ 18.0548, -17.9986,   8.9990,  -3.6364],
        [ -4.9763, -20.1125,  25.8310,  -2.4754],
        [ -5.1277,   4.5308, -13.0410,   6.6457],
        [ -2.5767, -20.1174,  24.6939,  -2.7570],
        [ -6.0336,   0.2182, -14.8522,  16.6909],
        [ -4.5891,  19.3399, -11.5653,  -7.8673],
        [ -4.0686,  21.4293, -11.9234,  -9.3476],


tensor([[-12.3338, -14.8596,  27.7172,  -9.0626],
        [-25.3258,  -2.7453, -22.1535,  16.0146],
        [ 27.8663, -21.7805,  -0.7977,  -4.2651],
        [ -5.7310, -11.2911,  21.2648,  -6.7980],
        [ 29.3812, -23.6585,   2.6561,  -4.4780],
        [ -6.1903, -13.0207,  22.8089,  -8.4060],
        [-18.2578,  -3.6198, -17.6924,  14.8456],
        [-26.6215,  -4.6905, -25.2008,  18.7031],
        [-15.7570,  -2.3139, -15.9839,  12.8042],
        [ 26.5057, -21.5581,   1.3683,  -5.2465],
        [-32.8442,  -6.7699, -28.5785,  23.9229],
        [ -3.3052, -12.7424,  24.4200,  -6.9848],
        [-33.2144,  -4.4643, -29.1700,  20.4928],
        [-32.9772,  -5.0539, -28.8846,  22.0623],
        [ -4.7776,  11.1746,  -5.1471,  -1.4212],
        [ -6.0234, -12.8463,  23.4255,  -7.0885],
        [ 27.7084, -22.0737,   0.9389,  -5.1193],
        [ 22.5510, -18.9807,   3.0800,  -4.8554],
        [ -8.9777,  14.0084,  -9.0808,  -4.6574],
        [ 24.4895, -21.5683,   3.8016,  -5.1449],


tensor([[-23.0983,  -4.0033, -22.5391,  17.4564],
        [-36.4553,  -6.2553, -33.0872,  24.0618],
        [ -8.8135, -12.4168,  23.1905,  -7.4232],
        [-25.2170,  -5.4868, -24.9748,  20.0427],
        [  0.4267, -13.4053,  20.6051,  -6.0265],
        [-37.4865,  -5.5043, -32.9844,  21.9304],
        [ 21.2940, -17.9771,   2.7938,  -5.1856],
        [-15.1121,  -2.0243, -16.5348,  12.9185],
        [ -6.9277,   8.7921,  -7.2231,  -2.9322],
        [ 13.3711, -16.9425,   7.8121,  -4.3019],
        [-21.1461,  -3.5736, -22.5279,  17.5365],
        [ -5.6149, -11.4220,  19.1685,  -6.9966],
        [ 18.9920, -17.5815,   5.6690,  -4.6762],
        [ -9.1466,  14.3184,  -8.4402,  -4.9998],
        [ -5.3240,  -9.7604,  19.5116,  -6.9232],
        [ -4.0644, -11.4132,  21.1044,  -6.4857],
        [ 22.5003, -19.9269,   4.2929,  -4.2085],
        [-30.3966,  -3.6186, -28.3430,  19.7319],
        [ 20.9679, -18.8999,   5.3667,  -5.0332],
        [ -4.7505,  13.9000,  -4.7522,  -2.9608],


tensor([[-24.1048,  -1.1172, -21.3995,  15.1099],
        [ -6.0204,  -9.6837,  21.6798,  -6.7402],
        [ 25.6089, -19.9538,   0.6321,  -3.7256],
        [ 20.1387, -19.2674,   5.0215,  -5.3856],
        [ -6.7620, -10.2458,  20.7599,  -6.4104],
        [ -7.0389,  16.2432,  -5.3852,  -7.0654],
        [ -4.1024,  10.3789,  -5.1868,  -0.0518],
        [ -6.9639, -16.3104,  27.0281,  -9.2565],
        [ 25.2553, -21.6880,   3.3636,  -4.4458],
        [ -6.3406, -13.8620,  25.6344,  -6.5963],
        [-10.4441, -15.9180,  28.2045,  -9.3780],
        [-10.0871, -11.7902,  23.3021,  -8.9073],
        [ -7.7827,  18.1443,  -4.8709,  -6.3286],
        [ 23.8820, -20.4526,   5.2540,  -5.9694],
        [ -5.7684,  -8.6601,  18.8261,  -6.9289],
        [ 23.8157, -18.4914,   1.1509,  -4.3253],
        [ -5.4484, -11.4518,  23.2584,  -6.5484],
        [-25.1585,  -4.2418, -24.8689,  18.9706],
        [-28.8757,  -5.6076, -26.6988,  20.7102],
        [-25.4762,  -2.9211, -23.6383,  17.0159],


tensor([[ 23.4052, -21.6081,   6.0050,  -5.6114],
        [-35.7350,  -3.4000, -31.7506,  20.2574],
        [ 24.2705, -19.0299,   2.3705,  -5.7142],
        [ 24.2021, -21.2430,   4.7958,  -3.9235],
        [ -6.2055, -11.2934,  21.7467,  -6.1948],
        [ -7.8607,  12.5872,  -8.6772,  -3.9884],
        [ 21.5219, -19.5648,   4.3720,  -6.3468],
        [-29.3168,  -3.3548, -25.9750,  18.8346],
        [ -7.5294,  11.4810,  -7.7110,  -4.4459],
        [ -6.6656,  13.6487,  -5.5778,  -4.9768],
        [ -7.5084, -10.3401,  21.3579,  -7.4395],
        [ 24.5232, -19.4020,  -0.4477,  -4.2322],
        [-31.2246,  -4.9522, -29.7749,  21.7195],
        [ 17.7374, -17.0066,   4.6781,  -4.1371],
        [-21.1418,  -6.6108, -22.8283,  19.5586],
        [ -7.1272,  11.4633,  -6.6486,  -1.7759],
        [ -6.9794,  16.2621,  -5.2273,  -5.2802],
        [ -6.1352,  -8.9890,  19.4700,  -6.1360],
        [ 27.3733, -21.3188,   0.7798,  -4.1752],
        [ 20.1260, -18.2315,   5.0719,  -5.4144],


tensor([[ -7.8458,  -9.9986,  21.1754,  -7.4800],
        [ 18.7670, -17.9430,   5.8338,  -4.2942],
        [ -7.3507,  14.5255,  -7.7408,  -4.6703],
        [ 26.1020, -21.7175,   1.6807,  -5.7506],
        [ -6.1125,  14.7034,  -4.3031,  -4.4613],
        [-10.7037, -11.4266,  26.3075,  -7.0425],
        [-28.8950,  -3.7761, -26.8265,  18.7178],
        [ -7.4280,  10.8345,  -7.5948,  -2.8155],
        [-34.6885,  -6.8439, -33.5090,  24.7467],
        [-25.7773,  -1.0136, -23.0865,  15.7916],
        [ -4.9082,  14.0540,  -5.6863,  -2.1305],
        [ -7.4272,  19.1488,  -5.6480,  -5.0230],
        [-19.5179,  -3.7615, -22.2183,  19.3002],
        [ -5.8957, -12.1310,  23.3214,  -6.0377],
        [ 22.3928, -18.3020,   3.8139,  -5.6961],
        [ 17.6599, -15.3078,   3.5607,  -3.6229],
        [ -9.8869, -13.1682,  24.9140,  -8.6954],
        [-11.2442, -15.4908,  30.7782,  -7.9985],
        [ 16.6782, -17.4686,   7.7422,  -4.6977],
        [ -8.0041, -14.9253,  26.8939,  -9.3929],


tensor([3, 3, 1, 3, 0, 1, 1, 3, 0, 3, 0, 3, 3, 3, 2, 2, 2, 2, 2, 0, 3, 1, 1, 1,
        3, 1, 0, 2, 1, 3, 2, 2])
tensor([[ -7.8138,  13.2387,  -7.7576,  -4.4671],
        [ -9.2656,  13.3223,  -9.0479,  -6.1119],
        [ -7.2921,  16.8601,  -5.8118,  -4.3872],
        [-28.7799,  -7.3586, -28.4271,  24.0668],
        [ -6.7009,  17.5531,  -4.9431,  -4.8154],
        [ 21.7421, -17.3150,  -0.3028,  -6.4217],
        [-10.9268, -12.5393,  26.9724,  -7.1345],
        [ -6.6593,  15.4282,  -6.0566,  -3.0353],
        [ -6.7259,  14.1449,  -6.3457,  -3.7248],
        [-26.0324,  -1.5939, -23.6553,  15.2713],
        [ -6.3659,  10.5902,  -5.9732,  -5.4022],
        [ -9.3244, -14.9905,  27.5568,  -9.5615],
        [ -7.5610,  17.4205,  -6.3183,  -5.4069],
        [-14.1536,  -2.0321, -15.0835,  11.3557],
        [ 21.4894, -18.3557,   3.4384,  -6.2049],
        [ 22.4804, -19.1703,   4.0435,  -6.3802],
        [ -6.4315,  13.0309,  -5.7170,  -5.0481],
        [ -6.3382,  14.1804,  -5.3934

tensor([[ -4.8099,  10.8183,  -3.9313,  -0.5996],
        [ -6.6263,  14.5624,  -4.2296,  -5.0464],
        [ -6.8723,  18.6024,  -5.2007,  -4.5796],
        [ -6.9435,  -1.5386,  -6.9525,   6.6563],
        [ 28.3361, -24.6724,   3.7090,  -4.7855],
        [ -6.4177,  12.5118,  -6.7487,  -3.5556],
        [ -7.6972,   8.1193,  -7.0737,  -3.5311],
        [ -7.5302, -11.9335,  23.7670,  -8.4255],
        [ 27.6348, -21.0774,  -0.4508,  -4.2063],
        [ -1.5300, -14.0280,  22.9246,  -6.2046],
        [ -7.2939,   9.6439,  -8.1679,  -3.5264],
        [ 13.7989, -16.2944,   8.0749,  -4.1740],
        [ 28.1592, -20.6526,   0.0840,  -5.2331],
        [-29.7949,  -4.4381, -29.2173,  22.1751],
        [ -8.5651,  14.1852,  -8.6040,  -5.1809],
        [-28.5477,  -6.5748, -27.0868,  21.7543],
        [ 13.2363, -17.1523,   8.5319,  -5.8271],
        [ -8.5482,  14.9945,  -8.9836,  -5.0113],
        [-10.2043, -14.0138,  28.1760,  -7.9320],
        [-10.7126,   8.7020,  -9.7566,  -0.8483],


tensor([[ -6.3266,  15.2430,  -5.0921,  -5.4255],
        [ -7.8595,  -2.1929,  -8.6830,   8.4006],
        [ 22.1376, -19.8162,   3.0276,  -4.7444],
        [ -4.8506,  11.9435,  -4.6245,  -1.9418],
        [ 24.9340, -20.7761,   1.3704,  -5.9966],
        [ -7.1285,  18.1012,  -5.6151,  -4.9853],
        [ -9.1118, -13.6191,  28.8226,  -8.2359],
        [ 19.0150, -15.7720,   1.2196,  -4.3986],
        [-11.4426, -12.2419,  26.5248,  -8.7081],
        [ -9.1854,  -9.9649,  21.7894,  -8.7022],
        [-11.2810, -14.8933,  29.7844,  -8.9315],
        [ -7.7878,  13.6030,  -7.8609,  -4.4390],
        [ 15.4897, -13.8536,   2.4002,  -5.9558],
        [ -5.9006,  14.3701,  -5.4073,  -3.4488],
        [-28.8840,  -3.3883, -25.5504,  18.0064],
        [ 17.9021, -18.6520,   8.4641,  -3.8996],
        [-25.4757,  -3.3395, -23.8646,  17.3604],
        [ 27.5062, -19.6162,  -0.6777,  -4.6744],
        [-14.0589,  -3.7950, -13.1450,  12.8596],
        [ -5.6253, -11.4395,  21.6842,  -5.4558],


tensor([1, 1, 1, 1, 3, 2, 2, 2, 1, 2, 0, 0, 0, 0, 1, 1, 3, 3, 0, 0, 3, 2, 2, 1,
        2, 1, 1, 1, 3, 0, 1, 0])
tensor([[ -4.0321,   9.8456,  -5.3797,  -1.2340],
        [ 23.9817, -20.1405,   4.0885,  -5.2168],
        [-16.9175,  -1.4521, -17.5829,  12.2858],
        [-35.2437,  -6.8723, -34.3437,  26.0005],
        [ -5.8708,  14.1265,  -5.7228,  -2.2459],
        [ 24.3407, -20.9607,   4.4073,  -5.0620],
        [ -5.4983,  -9.1705,  16.1113,  -5.8510],
        [ -6.4350, -12.7575,  23.8575,  -9.3179],
        [-26.1184,  -3.3548, -24.5978,  17.6904],
        [ 24.2955, -19.5966,   3.4743,  -6.1176],
        [-23.5814,  -1.9550, -20.9814,  15.4163],
        [ -4.6343,  11.9952,  -5.1438,  -2.5398],
        [ -4.4548,  10.5141,  -4.6441,  -1.2041],
        [  6.8407, -16.7011,  15.5504,  -6.7353],
        [ -7.5908,  13.7355,  -8.0072,  -4.4223],
        [-23.4192,  -2.7278, -21.6234,  15.7530],
        [-26.9020,  -5.5404, -27.5077,  21.9350],
        [ -8.4304, -14.1220,  28.7125

tensor([[-19.7842,  -0.9564, -19.8391,  15.7889],
        [  0.9788, -12.4390,  16.0750,  -6.4995],
        [ -8.9819, -12.9837,  25.8988,  -7.4768],
        [ -8.0942,   7.8908,  -9.6101,  -2.9361],
        [ -7.7079,  11.8752,  -8.4046,  -3.6826],
        [ -6.3947,  13.8296,  -5.0703,  -3.4841],
        [ 24.1550, -21.8709,   5.0727,  -5.2613],
        [ -6.9633,  -8.9739,  18.5774,  -6.7470],
        [ 22.0005, -17.7282,   2.3109,  -3.7157],
        [-11.3636, -12.6417,  26.6441,  -8.2973],
        [ -5.6445,  15.0495,  -4.5902,  -2.8113],
        [ -6.2371,  14.3665,  -5.5654,  -2.9985],
        [ -5.6842, -10.4259,  20.2248,  -7.6763],
        [ -9.1903,  16.5920,  -9.3544,  -6.7127],
        [ -9.5155,  13.3187,  -9.9100,  -5.7155],
        [ 19.9667, -17.4113,   3.9480,  -5.4814],
        [-26.4344,  -6.3314, -25.1696,  21.6589],
        [-19.0831,  -4.8496, -20.2379,  18.2293],
        [ -9.3967, -12.8413,  25.6328,  -6.9958],
        [ -7.7818, -12.2347,  24.2619,  -7.3298],


tensor([[-10.4598, -14.2645,  29.0618,  -7.2438],
        [ 21.0874, -18.5659,   5.5796,  -5.6940],
        [-11.0550,  15.9476, -10.3607,  -6.9501],
        [ -6.7705, -13.6492,  24.6837,  -6.0244],
        [ -0.6759, -14.5569,  21.7611,  -8.9701],
        [ -9.5167,  13.2932,  -9.5544,  -5.5327],
        [ -5.8050, -13.5680,  24.0529,  -9.9543],
        [ -8.3974,  13.0852,  -8.0673,  -4.7834],
        [-28.1500,  -4.1377, -26.4007,  19.1170],
        [ -6.9198,  17.8629,  -5.5108,  -4.3787],
        [ 21.3255, -17.1850,   2.3657,  -5.9861],
        [-21.3878,  -6.2320, -20.8015,  20.3762],
        [ -9.8904,  13.5725, -10.1383,  -6.2166],
        [ 22.9191, -19.5613,   2.4472,  -5.6407],
        [ 15.5538, -17.0859,   7.9379,  -4.1824],
        [ 21.0937, -19.1013,   5.0409,  -4.5094],
        [ 25.3528, -20.2356,  -0.2446,  -6.4167],
        [ -6.5852,  17.1167,  -5.2501,  -4.5955],
        [ 17.7594, -15.6479,   4.3523,  -5.0003],
        [ -6.3001,  15.4964,  -6.4577,  -3.8691],


tensor([[-20.9375,  -1.9851, -18.6532,  13.7671],
        [ -7.9867, -13.1230,  25.5913,  -8.6417],
        [-23.6195,  -5.0911, -22.2384,  16.4360],
        [ -8.3839, -10.0386,  19.7729,  -6.4094],
        [ 21.1451, -17.9690,   3.8923,  -4.7737],
        [ 22.6201, -18.2794,   3.3745,  -5.7348],
        [ -7.8941,  19.4325,  -5.2286,  -6.2807],
        [ -6.2535,  15.5796,  -5.9843,  -3.6581],
        [ -4.9146,  11.3829,  -5.9363,  -0.8655],
        [  1.0220,  -9.6807,  13.1575,  -4.8357],
        [ 27.5230, -20.7512,  -0.5217,  -5.2148],
        [-25.0804,  -1.5737, -22.0487,  14.5403],
        [ -0.4909,  -9.7811,  14.0041,  -5.0359],
        [ 27.0467, -21.1776,  -0.8103,  -4.4848],
        [ -5.8850,  10.4961,  -5.9640,  -3.1672],
        [ 20.3748, -18.7502,   5.4908,  -4.9631],
        [ -6.6025,  15.7762,  -5.0028,  -4.4478],
        [ -7.7842,  12.7986,  -8.4697,  -4.4435],
        [ -6.4942, -10.5819,  22.2889,  -7.0622],
        [ -7.6192,  16.1458,  -6.0097,  -6.0959],


tensor([[ 17.6756, -17.1324,   5.8312,  -4.4418],
        [ -7.4981, -15.9483,  24.0339,  -8.2048],
        [-26.1584,  -9.4348, -26.9510,  25.3760],
        [ -6.8695, -10.3785,  20.0625,  -7.3486],
        [-21.8599,  -2.9524, -21.6500,  16.4762],
        [ -6.5458,   9.6244,  -6.3891,  -3.8330],
        [ -4.9870, -10.1107,  19.2282,  -5.9446],
        [-10.9449,  -9.7715,  25.0816,  -7.1507],
        [ -6.5650,  17.2168,  -4.5396,  -4.7818],
        [ -0.3451, -12.4022,  20.3778,  -6.3107],
        [ -5.2011, -13.6349,  23.0415,  -7.8097],
        [-33.4649,  -2.9906, -29.9937,  19.5865],
        [ -6.6716,  14.9712,  -4.3478,  -5.2935],
        [ 16.4417, -13.9738,   4.1367,  -4.1219],
        [ -8.5526,  11.1114,  -9.2165,  -3.1190],
        [-23.5554,  -4.4106, -23.1280,  18.2372],
        [ -7.9631, -12.5896,  24.9545,  -6.7671],
        [-38.0341,  -6.2349, -33.5703,  24.6213],
        [-31.6986,  -5.9949, -29.9810,  22.3917],
        [ -8.0695, -12.4441,  24.0115,  -7.1951],


tensor([[ -7.4317,   8.2045,  -7.6424,  -1.2326],
        [-10.2143,  16.9103, -10.3260,  -6.9090],
        [-26.4173,  -7.5379, -26.6817,  25.0319],
        [-14.5812, -14.8925,  29.8723,  -8.3342],
        [ 21.3351, -18.2980,   4.7789,  -5.9836],
        [ 25.0353, -19.5948,   1.1771,  -3.7866],
        [ 25.9709, -20.4999,  -0.8546,  -6.1287],
        [-10.5149, -15.1495,  27.5150,  -8.9812],
        [ -5.2912, -11.8822,  20.8985,  -7.2295],
        [ 22.8486, -22.0691,   6.7941,  -5.0606],
        [ -4.8958,   9.7375,  -5.0711,  -2.9577],
        [ 22.1758, -20.7217,   5.0008,  -7.1729],
        [ -6.6654,  14.7561,  -5.4372,  -3.6730],
        [-21.8944,   2.6783, -19.5443,  12.2367],
        [ -5.8323, -15.3166,  24.6453,  -8.3824],
        [ 25.7533, -20.2356,   0.9102,  -4.3845],
        [ 22.2355, -18.7200,   3.1856,  -4.8327],
        [-29.3448,  -4.2798, -27.6186,  20.8607],
        [-16.9448,  -1.1838, -15.7491,  11.0509],
        [-22.6000,  -4.2153, -21.5024,  16.1574],


tensor([[ -6.6076, -12.8471,  23.0932,  -7.6488],
        [ 23.7658, -19.3910,   1.9560,  -4.6169],
        [ -9.6433,  14.8950,  -9.6984,  -6.5408],
        [ -3.8894, -12.4655,  21.2183,  -7.6796],
        [ -9.3495, -10.2694,  21.9440,  -6.9569],
        [ 23.8216, -19.0733,   0.4849,  -5.3136],
        [ -4.2204, -12.9388,  20.3227,  -6.3962],
        [ -6.5997,  16.0397,  -4.1485,  -4.6256],
        [ -7.3654,  18.0469,  -5.2432,  -5.7489],
        [ -4.8059,  12.8026,  -5.7530,  -2.0145],
        [ 18.7735, -17.3737,   5.4900,  -4.7742],
        [ -7.1640, -14.6243,  25.8791,  -8.6103],
        [ 15.2204, -14.2528,   3.2808,  -7.0416],
        [ -6.2597, -11.5249,  21.0766,  -8.2800],
        [ -7.9123,  16.2523,  -7.5976,  -5.4546],
        [ 17.3062, -17.7905,   6.7833,  -5.2072],
        [ -6.4757,   7.9272,  -6.5711,   0.4167],
        [ -7.8595,  11.8893,  -7.0283,  -5.1867],
        [ 19.1719, -17.7683,   3.9748,  -4.4092],
        [ 18.7519, -18.7115,   5.8751,  -5.2274],


Train Epoch: 3 [3168/24754 (13%)]	Loss: 0.000063
Train Epoch: 3 [6368/24754 (26%)]	Loss: 0.000034
Train Epoch: 3 [9568/24754 (39%)]	Loss: 0.000430
Train Epoch: 3 [12768/24754 (52%)]	Loss: 0.000000
Train Epoch: 3 [15968/24754 (64%)]	Loss: 0.004219
Train Epoch: 3 [19168/24754 (77%)]	Loss: 0.000000
Train Epoch: 3 [22368/24754 (90%)]	Loss: 0.000004
tensor([[ 11.7389,  -8.2516,  -3.5855,  -3.0500],
        [ 17.1791, -11.5547,  -4.2348,  -2.7523],
        [-16.0350, -10.0469,  18.0832,  -8.4245],
        [-46.5852,  -7.7359, -41.5747,  27.0962],
        [-14.1286,  18.3343,  -6.0398,  -6.1660],
        [-11.3541, -11.2475,  18.0488,  -7.6284],
        [ -3.2279,  -8.9938,  13.4332,  -4.8793],
        [-18.7136, -12.8714,  20.5929,  -9.6236],
        [ 15.9549, -13.1172,  -0.2298,  -3.3999],
        [ 16.5208, -12.1578,  -4.9395,  -3.7327],
        [-11.7373,  20.4097,  -4.6242,  -9.6932],
        [-25.1747,  -3.9369, -22.3863,  17.7696],
        [-13.4515,  14.3099,  -8.0938,  -2.7033],
   

tensor([[-13.9974,  11.2644, -10.5214,  -1.9461],
        [-25.0710,  -6.2228, -23.2777,  16.2435],
        [-17.0861,  15.8798, -12.7488,  -5.6457],
        [-34.4913,  -9.1211, -28.4647,  26.5845],
        [ -8.4532,  14.2822,  -3.5211,  -8.3994],
        [-19.2793,  -3.7253, -16.7019,  14.9337],
        [ -9.0761, -14.4692,  16.8776,  -8.2717],
        [-13.2704,  19.6355,  -6.7716,  -4.9419],
        [ -8.8652,   9.0241,  -5.4221,  -1.5923],
        [ 10.4342, -11.2709,   3.4139,  -3.7940],
        [-25.4713,  -6.2954, -23.3451,  19.5086],
        [-28.5328,  -7.9634, -24.1791,  20.7618],
        [ -9.2091,  12.1440,  -5.2066,  -7.3489],
        [ 14.0308, -12.4790,   1.4613,  -3.3381],
        [ 14.2621, -12.5978,   1.6985,  -3.8525],
        [-33.2416,  -8.8785, -29.7890,  25.6547],
        [ -7.3362, -11.2624,  16.3044,  -7.9009],
        [-10.7063, -11.7206,  15.8026,  -7.4443],
        [-24.8955,  -4.2539, -21.6743,  15.2716],
        [ -7.8482,  -7.2591,  11.4307,  -5.7296],


tensor([[-33.5381,  -5.3364, -30.9468,  21.1058],
        [ -8.1539, -11.0218,  17.7557,  -5.7999],
        [-35.5536,  -5.8168, -32.5562,  20.3685],
        [ -6.8354,  -7.5051,  13.8787,  -6.3466],
        [-14.1908,  13.1551,  -9.2190,  -3.0483],
        [-32.2451,  -5.4626, -29.6638,  18.0398],
        [-24.8079,  -4.0498, -22.2411,  18.2377],
        [ 12.8890, -11.9748,   0.9076,  -3.5923],
        [ 11.1493,  -9.2766,  -0.7996,  -2.4232],
        [ -8.1827,  -8.0067,  16.0198,  -5.1897],
        [ -5.5681, -12.1109,  14.7507,  -9.0731],
        [-12.7343,  21.3097,  -5.7837, -11.0616],
        [ 15.8107, -13.4279,   0.4235,  -3.1682],
        [ 14.3231, -14.8450,   1.3081,  -4.2385],
        [ 13.8418,  -9.9300,  -3.4729,  -2.3298],
        [ 16.2476, -13.0658,  -2.2653,  -2.9752],
        [-10.0314,  15.9852,  -5.0876,  -3.9746],
        [-27.6480,  -6.9764, -24.1218,  18.2556],
        [-33.1999,  -8.6756, -28.7809,  27.8352],
        [ 14.0472, -14.1007,   2.6118,  -4.4482],


tensor([[ 1.3713e+01, -1.2771e+01,  1.4404e+00, -3.8891e+00],
        [ 1.4299e+01, -9.9522e+00, -3.0791e+00, -3.4419e+00],
        [-4.1159e+01, -8.6073e+00, -3.9009e+01,  2.5797e+01],
        [-8.1290e+00,  1.3739e+01, -3.4633e+00, -8.2384e+00],
        [-1.0565e+01,  1.4482e+01, -4.7983e+00, -2.4806e+00],
        [-7.0656e+00, -9.4113e+00,  1.4764e+01, -6.4490e+00],
        [-6.7961e+00, -1.1744e+01,  1.6420e+01, -8.6951e+00],
        [ 1.3758e+01, -9.2401e+00, -3.8326e+00, -2.4484e+00],
        [-9.0128e+00,  1.5294e+01, -3.7535e+00, -8.9543e+00],
        [-4.7728e+00, -1.0860e+01,  1.8954e+01, -7.8294e+00],
        [-1.2080e+01, -1.0833e+01,  1.5454e+01, -7.4714e+00],
        [-8.9957e+00,  1.6491e+01, -2.5161e+00, -6.7219e+00],
        [ 1.9103e+01, -1.2767e+01, -6.1810e+00, -2.9942e+00],
        [-8.7030e+00,  1.4787e+01, -4.0868e+00, -8.8236e+00],
        [ 1.5213e+01, -1.3409e+01,  1.6712e-02, -3.9827e+00],
        [-2.6752e+01, -7.5851e+00, -2.2781e+01,  2.6673e+01],
        

tensor([[ 14.6112, -13.0717,  -0.8156,  -4.1351],
        [ 10.9788,  -8.5257,  -2.8768,  -5.0922],
        [-25.3688,  -9.0091, -23.2762,  26.5031],
        [-34.1669,  -6.8054, -31.6224,  18.9635],
        [-22.6204,  -3.7875, -20.5908,  13.3428],
        [-29.5597,  -9.8412, -25.0441,  22.0823],
        [-26.9366,  -5.5470, -25.4297,  16.1907],
        [-11.5391,  19.9156,  -4.4000, -10.1059],
        [-12.8924,  21.9746,  -6.3831,  -6.6149],
        [ 11.5306, -12.4737,   1.3779,  -3.8403],
        [ -4.8099,  -8.5065,  16.1135,  -6.5719],
        [-11.6102,  17.4097,  -7.1566, -10.1469],
        [-29.4249,  -7.1100, -27.5912,  19.6956],
        [ -9.9935,  16.5941,  -4.0682, -10.1151],
        [-11.8590,  -0.4658, -10.4895,   5.7132],
        [-25.9678,  -9.5101, -22.5141,  24.0197],
        [-13.2076,  -8.3010,  14.4417,  -6.7915],
        [ 12.2944, -11.3360,   0.6102,  -3.1229],
        [ 13.7660, -12.0646,   0.8039,  -3.5540],
        [-12.4745,  11.9507,  -9.0906,  -2.9732],


tensor([[ 12.8216, -12.5022,   1.1579,  -3.8033],
        [ 12.5202, -10.9681,   0.3749,  -3.5169],
        [ -6.9356, -12.3690,  23.8381,  -8.1680],
        [-11.6019,  18.1705,  -5.4299,  -4.7283],
        [-30.3839,  -7.6929, -30.0107,  19.1266],
        [ 22.2689, -16.1384,  -5.5611,  -3.8611],
        [ 14.6124, -12.9451,  -1.7128,  -3.8674],
        [-15.0882,  17.2436,  -9.5874,  -4.2617],
        [-14.4905,  18.7134,  -8.3244,  -4.1629],
        [-13.2150,  21.4668,  -5.8261,  -4.7668],
        [ -8.8680,  -9.2500,  13.2920,  -7.1453],
        [-11.8278,  11.5118,  -8.0134,  -3.0654],
        [-12.5330,  15.9026,  -7.9685,  -2.7446],
        [-37.7475,  -7.7116, -35.9464,  20.7024],
        [-16.2626, -11.2240,  20.0216,  -8.8067],
        [-32.5565, -11.9037, -28.4653,  30.2036],
        [ 15.2211, -12.5121,  -0.3814,  -3.8487],
        [-16.1341, -13.4748,  22.3165,  -8.3794],
        [ -8.8668,  -9.4537,  14.9643,  -6.8506],
        [-16.5826,  18.7933, -11.2777,  -4.8149],


tensor([[ 1.4199e+01, -1.4369e+01,  3.2644e+00, -3.3549e+00],
        [-1.2394e+01,  1.7109e+01, -5.0868e+00, -3.5972e+00],
        [-9.3175e+00,  1.5634e+01, -3.7875e+00, -9.5132e+00],
        [-6.9148e+00, -1.1166e+01,  1.2878e+01, -5.4510e+00],
        [-1.0885e+01, -1.1836e+01,  1.9150e+01, -7.4943e+00],
        [-1.4756e+01,  1.4253e+01, -1.0241e+01, -3.5667e+00],
        [-7.4553e+00, -8.9853e+00,  1.4364e+01, -7.4145e+00],
        [-1.1680e+01, -1.0228e+01,  1.5425e+01, -7.0748e+00],
        [-1.0013e+01, -8.6128e+00,  1.4667e+01, -7.5008e+00],
        [-6.1603e+00, -9.5368e+00,  1.3752e+01, -5.2751e+00],
        [-8.4142e+00, -1.1200e+01,  1.3533e+01, -6.9290e+00],
        [-1.0155e+01,  1.8301e+01, -3.4161e+00, -8.4694e+00],
        [-8.0699e+00,  1.1635e+01, -4.9581e+00, -3.0186e+00],
        [ 1.3786e+01, -1.1787e+01, -1.1630e-02, -3.1433e+00],
        [-1.1419e+01, -1.1389e+01,  2.0918e+01, -7.3192e+00],
        [-3.4955e+01, -1.0890e+01, -3.2364e+01,  2.8217e+01],
        

tensor([[-1.3375e+01,  1.4776e+01, -7.7938e+00, -2.9213e+00],
        [ 1.6609e+01, -1.3016e+01, -7.3544e-01, -3.6813e+00],
        [ 1.0202e+01, -1.0796e+01,  3.0332e+00, -3.3351e+00],
        [-1.3433e+01,  2.2428e+01, -5.7823e+00, -9.6702e+00],
        [-8.1230e+00,  1.2440e+01, -4.8818e+00, -7.6380e+00],
        [-3.2271e+01, -7.9497e+00, -2.8918e+01,  2.5838e+01],
        [-9.3184e+00,  5.7431e+00, -7.4819e+00, -4.1291e-02],
        [-1.3971e+01, -1.2913e+01,  1.7187e+01, -8.0437e+00],
        [ 1.6123e+01, -1.2784e+01, -3.0835e+00, -3.7793e+00],
        [ 1.5794e+01, -1.1145e+01, -5.3207e+00, -4.7440e+00],
        [ 1.4164e+01, -9.4390e+00, -2.9059e+00, -4.4781e+00],
        [-7.7350e+00, -8.2987e+00,  1.3196e+01, -5.4634e+00],
        [-1.0730e+01,  1.8113e+01, -4.2874e+00, -6.9943e+00],
        [-1.3960e+01, -1.2227e+01,  1.9981e+01, -8.1168e+00],
        [-1.8843e+00, -7.1097e+00,  1.1147e+01, -5.4564e+00],
        [ 1.5093e+01, -1.2155e+01, -2.7821e-01, -2.9044e+00],
        

tensor([[ 11.9382,  -9.7281,  -0.9862,  -1.9797],
        [-15.8828,  24.6901,  -7.8631,  -7.4008],
        [-10.2532, -10.2560,  13.9171,  -7.3499],
        [-36.9322,  -6.0731, -32.4190,  18.5987],
        [ -2.1594,  -8.8553,  13.2577,  -4.9813],
        [-11.9002, -10.1157,  16.5178,  -6.3302],
        [-46.9125, -10.4155, -44.0601,  29.9370],
        [-28.3331,  -8.2719, -27.0019,  24.9739],
        [ 16.1935, -14.5422,   1.7242,  -3.9883],
        [-32.6390,  -8.3571, -29.4623,  22.9164],
        [-12.5026,  17.9610,  -7.5062,  -4.1881],
        [  7.9616, -11.1693,   1.9108,  -3.2519],
        [ -2.7011,  -8.1772,  12.0561,  -5.3784],
        [ 13.0051, -11.9586,  -1.1964,  -3.0971],
        [ 17.5736, -12.0977,  -6.8772,  -4.2904],
        [-16.0858,  15.5565, -11.7377,  -4.0540],
        [-12.8947, -10.6051,  16.2186,  -7.1664],
        [ 13.6608, -12.5967,  -1.2553,  -3.7145],
        [ -9.9318,  15.8751,  -4.9135,  -3.4949],
        [-14.6733,  24.5973,  -5.1308,  -7.8801],


tensor([[ -5.8203,  -8.5818,  17.2187,  -5.5978],
        [-24.0101,  -4.7684, -22.9760,  16.8024],
        [-10.7706, -10.4740,  16.1142,  -7.0483],
        [-11.6102, -11.1492,  11.5286,  -6.3249],
        [ 16.3016, -12.9946,  -1.1300,  -3.5220],
        [-21.7474,  -3.1716, -18.4375,  15.6568],
        [ -9.0493,  14.3926,  -5.2219,  -8.6647],
        [-14.9884,  21.4826,  -8.8675,  -5.3918],
        [  9.2327,  -8.6962,   1.4407,  -3.4310],
        [ -9.3832,  -9.6273,  16.9250,  -8.1721],
        [ -9.4280,  17.2164,  -4.6144,  -5.6668],
        [ -3.9361,  -9.3878,  15.8081,  -5.9120],
        [ 14.9573, -12.1252,   0.1490,  -3.7609],
        [ -7.7026,  -8.6445,  11.7229,  -7.0597],
        [ -6.8190,  12.1680,  -3.0318,  -2.4998],
        [-30.5395,  -3.9320, -27.3834,  16.6829],
        [-29.2275,  -7.5242, -27.6366,  20.1811],
        [-11.2877,  20.4338,  -4.3737,  -8.0881],
        [ -2.8809, -11.7459,  13.1180,  -6.3806],
        [-11.6453, -11.4790,  18.3486,  -7.7958],


tensor([[-11.1687,  20.6392,  -3.6378,  -8.2768],
        [-10.6973, -11.3067,  13.8444,  -6.8097],
        [ -8.7673,  17.3839,  -3.4830,  -7.1220],
        [-10.9875, -10.9036,  15.6410,  -8.2978],
        [-10.0775,  14.1486,  -4.4163,  -2.1727],
        [ -9.6426,  16.5582,  -4.3103,  -8.1829],
        [  1.6256, -10.9203,  10.2180,  -6.8490],
        [-11.6432, -12.5907,  15.3635,  -6.6598],
        [-21.9816,  -6.8273, -19.4460,  16.7026],
        [ -1.6400,  -9.8438,  10.5513,  -5.7974],
        [ 13.3973,  -9.3035,  -3.3117,  -2.3508],
        [  8.0441,  -8.3873,   0.8428,  -4.5726],
        [ 10.9112,  -8.3727,  -3.4268,  -5.0235],
        [-29.3489,  -5.8638, -26.1886,  22.5200],
        [ -7.6363,  14.2118,  -2.2570,  -8.9081],
        [ -7.6705,  -8.0039,  11.4829,  -6.7132],
        [ 10.6851, -12.0752,   3.1127,  -4.0060],
        [ 12.5088, -10.4018,  -1.5071,  -3.4322],
        [ -8.6717,  -8.8014,  10.7954,  -5.0659],
        [ -9.3400,  17.0993,  -4.5846,  -5.4461],


tensor([[-22.9179,  -3.4411, -20.2301,  13.8278],
        [-13.2187,  20.5717,  -7.1054,  -4.8846],
        [-30.2915,  -5.9989, -28.0902,  17.3226],
        [ 10.8631, -10.7321,   1.6614,  -2.6543],
        [-11.6287,  19.7522,  -5.3013,  -6.2998],
        [ 11.7252, -10.6232,   0.8635,  -3.3391],
        [-26.7551,  -3.9369, -22.7743,  16.2443],
        [-26.8841,  -5.8199, -23.2321,  21.2198],
        [-13.3906,  17.9624,  -7.1667,  -4.3823],
        [ -8.8066,  -8.4929,  12.6107,  -7.0025],
        [-10.9518, -11.0329,  20.0855,  -7.2020],
        [ 11.5524, -10.4058,   0.9728,  -2.5376],
        [ 11.8565, -12.5736,   2.0384,  -3.6846],
        [ 11.8412, -12.1287,   3.5031,  -3.6276],
        [-30.4492,  -4.1068, -26.9681,  17.4382],
        [-39.0392,  -6.8061, -36.2319,  23.6265],
        [-16.3366,  18.8072, -11.5054,  -4.1846],
        [-19.7938,  24.7327, -13.0405,  -7.8884],
        [ 10.6764, -10.4566,   0.1308,  -2.9492],
        [-12.0679, -11.8823,  19.7044,  -7.6826],


tensor([[-1.0302e+01, -1.1689e+01,  1.7065e+01, -8.0660e+00],
        [-7.5876e+00, -8.2577e+00,  1.6131e+01, -5.9091e+00],
        [-9.5346e+00,  1.6209e+01, -3.8621e+00, -9.9682e+00],
        [ 1.2135e+01, -1.0503e+01,  1.5915e-01, -2.5488e+00],
        [ 1.2518e+01, -9.9542e+00, -1.3592e+00, -2.5109e+00],
        [-3.0170e+01, -4.5707e+00, -2.7859e+01,  1.9147e+01],
        [-2.5259e+01, -3.7026e+00, -2.1642e+01,  1.5320e+01],
        [-3.8808e+01, -8.5032e+00, -3.6632e+01,  2.3507e+01],
        [-6.9662e+00, -8.0465e+00,  1.6163e+01, -6.2679e+00],
        [-3.0612e+01, -4.4950e+00, -2.7902e+01,  1.6687e+01],
        [ 1.0865e+01, -9.6670e+00, -1.4976e-02, -2.3848e+00],
        [-1.4504e+01,  2.0177e+01, -7.9541e+00, -5.4019e+00],
        [ 1.4529e+01, -1.4338e+01,  2.4321e+00, -3.9665e+00],
        [-1.0452e+01,  9.4830e+00, -4.9830e+00,  2.9983e-01],
        [-1.6153e+01, -4.2115e+00, -1.4445e+01,  1.7172e+01],
        [-1.6731e+01,  1.5823e+01, -1.2552e+01, -4.8808e+00],
        

tensor([[ 13.8100, -10.6891,  -3.1186,  -3.9063],
        [-13.1654, -11.8342,  18.9783,  -9.0309],
        [ 11.8624, -12.6056,   2.1057,  -4.1460],
        [ -9.9644,  18.2528,  -3.6715,  -6.0545],
        [-11.4358,  19.6614,  -5.5639,  -4.1160],
        [ -8.3021,  -9.0369,  12.5052,  -5.9811],
        [ 15.5047, -13.4374,  -0.7635,  -3.3144],
        [ -8.3711,  13.0175,  -2.5804,  -6.2248],
        [-10.3789, -10.0662,  16.8973,  -6.6611],
        [ 14.7376, -13.4550,   0.5988,  -3.7118],
        [ 10.3106, -10.2149,   1.6487,  -3.2500],
        [ 14.5011, -13.1937,   1.4853,  -2.9467],
        [-13.2174,  18.2376,  -8.0894,  -4.5770],
        [-12.7858,  20.8290,  -5.4238,  -4.3008],
        [ -5.4759,  -9.0583,  15.2006,  -8.6674],
        [ 11.8994, -10.4344,   0.0518,  -4.1548],
        [-27.1215,  -8.6874, -22.8404,  18.7117],
        [ 10.7028, -12.5378,   2.3245,  -4.2193],
        [ -1.7289,  -8.6825,   7.8450,  -4.4552],
        [-12.3776,   8.9224,  -9.0301,  -1.6410],


tensor([[-21.6227,  -1.7807, -18.5841,  14.9839],
        [ 18.6061, -12.7479,  -4.2887,  -2.9903],
        [ 13.5646, -12.7525,   1.3435,  -3.6873],
        [-17.5888,  -4.5359, -12.4988,  16.7392],
        [-23.7202,  -2.6130, -21.0426,  15.8025],
        [ -3.6183,  -7.8303,  13.0997,  -5.6223],
        [ 16.1531, -14.3902,  -1.0459,  -4.0711],
        [-26.1387,  -5.6869, -22.6516,  19.1427],
        [-16.0462,  16.4254, -11.8625,  -5.1771],
        [-10.9780,  18.9546,  -3.9997,  -8.4071],
        [ 15.3285, -11.8594,  -3.9618,  -2.8054],
        [-23.9235,  -5.9073, -21.9837,  21.4094],
        [ 16.3640, -14.1896,   0.8034,  -4.2664],
        [ -8.6527,  13.7402,  -3.7859,  -5.1784],
        [ 11.9517, -10.1580,  -0.4171,  -2.1749],
        [-34.1666,  -8.9071, -29.7063,  23.3689],
        [ 12.8457,  -9.9325,  -2.5356,  -2.6221],
        [ -8.4610, -10.2166,  14.1171,  -5.7442],
        [ 15.8674, -13.4668,  -0.0644,  -2.9414],
        [-29.8627,  -8.7404, -25.2814,  26.2730],


Train Epoch: 4 [3168/24754 (13%)]	Loss: 0.000016
Train Epoch: 4 [6368/24754 (26%)]	Loss: 0.000004
Train Epoch: 4 [9568/24754 (39%)]	Loss: 0.001260
Train Epoch: 4 [12768/24754 (52%)]	Loss: 0.000081
Train Epoch: 4 [15968/24754 (64%)]	Loss: 0.000009
Train Epoch: 4 [19168/24754 (77%)]	Loss: 0.000005
Train Epoch: 4 [22368/24754 (90%)]	Loss: 0.000473
tensor([[ 12.8747, -12.7704,  -1.1384,  -6.5754],
        [-31.8626,  -9.5102, -30.5243,  29.4958],
        [-25.8387,  -6.2942, -23.5489,  21.9388],
        [-37.5580,  -6.8659, -36.8307,  24.4184],
        [-26.7776,  -5.2636, -24.3547,  19.5144],
        [-14.6224,  16.5428, -15.6851,  -7.2214],
        [-20.6570,  16.2970, -23.6135,  -8.2918],
        [-26.2752,  -7.3795, -24.1809,  22.0345],
        [-11.5849, -16.5626,  22.4698, -17.2244],
        [ 20.0220, -15.0390,  -2.1866,  -5.7756],
        [-35.0419,  -2.9930, -33.8531,  14.8583],
        [ -7.7471, -14.1087,  15.8165, -15.2464],
        [ -5.9918, -12.4903,  16.1539, -15.7299],
   

tensor([[-11.7447,  17.2496,  -8.3075, -10.7301],
        [ 26.5748, -17.5199,  -8.4509,  -5.9466],
        [ -8.8153,  12.1490,  -7.1122,  -6.8979],
        [ 14.2145, -13.4956,  -0.4620,  -7.3445],
        [ 16.8199, -13.2409,  -2.2797,  -5.5047],
        [ 19.8561, -14.2876,  -3.3906,  -7.7681],
        [-25.9840,  -4.1980, -25.5163,  14.1014],
        [ -0.0825, -11.0710,   9.6253, -13.3884],
        [-10.7249,  13.8317,  -8.0070,  -9.8692],
        [ 18.1781, -12.0847,  -7.4134,  -4.7588],
        [ 19.2090, -14.5297,  -4.3040,  -5.6507],
        [ 18.6075, -14.9310,  -5.1154,  -6.7587],
        [ 16.8932, -15.1021,  -3.2406,  -7.6598],
        [  1.3712, -11.8611,   9.9785, -10.6062],
        [ 16.1292, -13.6777,  -2.4327,  -7.4247],
        [-10.6108,  12.9253,  -7.7139,  -8.7129],
        [-10.4282,  15.3210,  -8.0965,  -9.5129],
        [-13.9728,  -2.8444, -12.7590,  10.4633],
        [-12.2894, -17.1646,  21.5953, -19.7856],
        [ 15.0625, -15.2540,  -0.3438,  -8.8123],


tensor([2, 3, 3, 0, 1, 1, 2, 3, 1, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 0, 1, 2, 1,
        0, 1, 3, 2, 2, 1, 2, 3])
tensor([[-11.2456, -15.3052,  18.6325, -15.8729],
        [  1.2114, -11.5033,   8.2129,  -7.7754],
        [ -5.2385, -12.3614,  14.2941, -15.7331],
        [ 12.7432, -12.3178,  -1.0789,  -7.2769],
        [-25.4440,  -4.6651, -25.9178,  17.1474],
        [ 16.0972, -13.3804,  -3.7546,  -6.0612],
        [-13.5369,  -2.8284, -14.3797,   9.9454],
        [-20.0094,  16.6888, -19.5291,  -8.7773],
        [-10.3691, -17.1581,  18.9804, -19.1834],
        [-14.0723,  18.4237,  -8.5661, -13.7551],
        [ -4.6203, -12.4700,  15.1159, -14.1186],
        [ 16.3693, -13.4171,  -2.2714,  -7.3822],
        [-11.3943,  16.5086,  -8.4132,  -9.9721],
        [ 22.1885, -13.2350, -10.2874,  -3.6317],
        [ -7.3853,   9.9031,  -5.5089,  -7.3124],
        [-13.0835, -17.1999,  20.0825, -18.8647],
        [-24.7486,  -4.5689, -24.1086,  16.3507],
        [ -8.4516, -15.5298,  19.8212

tensor([[-20.4394,  -8.0350, -19.1371,  22.8840],
        [-18.5269,  12.6873, -18.8859,  -7.2474],
        [ 22.9690, -16.7914,  -4.0833,  -7.9945],
        [ -8.6637, -13.7626,  18.8406, -14.7057],
        [-29.8211,  -3.8293, -29.2113,  16.8623],
        [ -1.8666, -11.8301,  12.2755, -13.3001],
        [-15.5791,  21.1891, -10.6825, -13.5222],
        [-25.7455,  -3.6888, -25.9974,  13.7329],
        [-11.4085,  14.1495,  -9.4270,  -8.0437],
        [ 20.0669, -16.4205,  -3.0764,  -9.9879],
        [ 18.3619, -13.2323,  -3.5185,  -7.8722],
        [ -4.2105, -11.7100,  11.8981, -12.1606],
        [ 15.7225, -13.4315,  -1.3954,  -6.6076],
        [ 12.8165, -12.1770,  -3.1279,  -6.9544],
        [ 21.3521, -14.3594,  -6.9719,  -5.0503],
        [ 20.8166, -13.9611,  -6.0534,  -4.6916],
        [ 20.3784, -16.3965,  -1.9238,  -7.8307],
        [ -2.0256, -11.9565,  11.5011, -14.8878],
        [-12.8678,  17.3805,  -8.0195, -12.2595],
        [-37.2577,  -6.6033, -38.3747,  17.6784],


tensor([[-35.7183,  -4.9610, -36.8199,  19.4508],
        [ -9.8511, -18.1729,  20.2611, -17.4605],
        [-10.4806, -12.2455,  18.4227, -17.1196],
        [-32.6369,  -7.7476, -32.5139,  20.9688],
        [ 20.0576, -15.5888,  -3.2212,  -9.0956],
        [-18.4031,  -5.5929, -16.1121,  16.2929],
        [-23.3399,  -2.3918, -22.1866,  13.1672],
        [ 21.9866, -17.2394,  -5.5147,  -7.2600],
        [-15.7115,  18.6435, -14.7027, -10.1396],
        [ 20.3059, -14.9990,  -4.0269,  -8.9707],
        [-14.1878,  17.0962, -12.0211,  -9.3006],
        [ -0.9322, -13.6147,  11.5548, -13.4820],
        [-13.8407,  18.6511,  -8.6637, -13.6155],
        [ 18.5143, -13.3035,  -4.3342,  -5.0416],
        [-17.3930,  18.9144, -15.5741, -10.0424],
        [-11.3154,  13.7508,  -8.1817, -10.3932],
        [-14.2199,  20.0161, -10.1645, -13.6063],
        [-22.4452,  -1.7063, -20.8624,  11.1117],
        [ -8.7484, -15.0660,  17.8802, -15.7253],
        [-11.7402,  14.6074,  -7.6256, -11.1059],


tensor([[ -6.3492, -12.0988,  13.2140, -12.6950],
        [ 20.7075, -15.9851,  -4.7532,  -6.4767],
        [-22.0052,  -7.4670, -21.1879,  24.2599],
        [ 26.2645, -17.5308,  -7.7104,  -5.7113],
        [-12.3615,  16.0147,  -8.2647, -11.6756],
        [-20.4479,  15.1611, -21.4611,  -7.7524],
        [-15.4088,  19.7734, -10.9017, -12.0268],
        [-27.6681,  -3.0064, -27.6623,  10.6817],
        [  6.4743,  -9.9500,   1.1936,  -8.7328],
        [-16.0817,  21.1158, -12.2422, -12.5335],
        [-32.3520,  -5.2403, -33.5382,  19.3716],
        [-29.0092,  -7.3842, -29.3414,  27.9419],
        [-20.2153,  -3.6374, -18.1636,  16.6399],
        [ 19.5515, -13.8328,  -7.8164,  -6.5637],
        [-20.4414,  15.4991, -20.7087,  -8.7233],
        [ 15.4198, -14.2732,  -1.5089,  -7.1347],
        [ -9.3804,  14.0066,  -8.8113,  -7.4740],
        [-13.6022,  13.3767, -13.2445,  -7.3172],
        [-12.7166,  -4.9995,  -9.6881,  17.5213],
        [ 18.5890, -15.9624,  -2.5552,  -7.6096],


tensor([[ -6.8745, -13.3072,  15.0308, -13.1504],
        [ -5.4131, -12.0868,  13.7055, -17.3737],
        [-10.1644,   9.4663, -10.1886,  -4.4224],
        [ -9.5126, -12.2087,  16.3294, -14.8390],
        [ -0.1027,  -9.9541,   8.0104,  -8.4792],
        [-10.1212, -14.4542,  18.1594, -14.7512],
        [-24.1720,  -1.6556, -25.0777,   8.1250],
        [-32.1158,  -3.0084, -32.9287,  10.8594],
        [-25.8418,  21.1304, -25.8089, -10.6459],
        [ 12.1742, -11.6348,  -0.6186,  -6.5710],
        [-36.2116,  -4.5807, -34.9931,  19.8444],
        [ 14.7119, -13.1963,  -1.1886,  -7.4722],
        [-25.0438,  -9.4150, -23.8505,  29.9649],
        [-19.9582,  -7.8861, -19.5386,  21.5482],
        [ -5.8533,  -7.7570,  10.7630,  -9.9722],
        [ -6.5076, -11.9821,  14.2310, -13.2828],
        [-18.5938,  -1.5947, -19.0305,   8.5912],
        [-42.2557,  -5.3165, -40.7007,  23.1038],
        [-11.2422,  15.2546,  -9.0274,  -9.6431],
        [ 17.9022, -16.0292,  -2.5763,  -8.3090],


tensor([[-28.5790,  -2.7499, -26.3385,  16.7429],
        [-12.7633, -17.4031,  21.4085, -19.8267],
        [ 19.9175, -14.7636,  -3.9869,  -8.9662],
        [ -8.5570, -13.4657,  16.3297, -16.1333],
        [ 18.3737, -14.8554,  -3.2184,  -8.2629],
        [-11.5324,  14.6177,  -8.7352,  -9.5607],
        [ 24.5851, -16.4183,  -8.2112,  -5.7855],
        [ 16.3827, -15.8711,  -2.8949, -10.2091],
        [-11.5234,   9.4548, -11.9479,  -5.2781],
        [-12.3740,   9.9386, -13.8810,  -5.4242],
        [ -8.8445, -14.0453,  16.9997, -17.2702],
        [ 17.0238, -14.9736,  -2.0284,  -7.9775],
        [-26.0654,  -8.5890, -24.3030,  25.4202],
        [-15.0123,  20.1154, -10.3050, -13.3305],
        [-12.7769,  18.3992,  -8.3938, -12.4512],
        [-16.8503,  18.7990, -15.4495,  -9.7458],
        [-28.1038,  -1.5136, -28.1829,  11.5951],
        [-15.5274,  18.6466, -14.9783,  -9.6653],
        [-12.2152,  16.5310,  -8.0708, -10.9955],
        [ 14.5435, -11.9888,  -4.7934,  -5.0570],


tensor([[-22.9874,  -9.5090, -22.2489,  27.5446],
        [ -9.8068,  12.2400,  -8.0362,  -6.8554],
        [ -6.5237, -13.9297,  15.0501, -16.0590],
        [-27.3822,  -3.0192, -27.5827,  13.4812],
        [-23.4759,  -1.9849, -22.5723,  13.4552],
        [-11.8860,  15.3560,  -8.7640,  -9.9411],
        [ 19.5286, -14.5421,  -2.1046,  -8.9602],
        [ 24.3758, -15.6480,  -8.5053,  -5.2234],
        [-16.3082,  14.2632, -16.1258,  -6.9438],
        [ 19.4915, -13.8169,  -2.4530,  -5.6502],
        [ 16.8765, -13.3620,  -3.5084,  -6.2330],
        [ -6.1647, -13.1570,  13.6609, -14.3152],
        [-10.9201,  13.7576,  -7.1568, -11.6355],
        [ 15.4134, -11.8361,  -2.3338,  -6.7660],
        [-23.1980,  -4.0144, -21.2287,  17.4511],
        [-17.5962,  13.7974, -17.9046,  -7.4159],
        [-22.0725,  -2.8329, -20.0912,  14.4314],
        [ 20.2408, -15.6684,  -3.1497,  -6.7498],
        [-26.7804,  -2.0854, -25.1488,  13.1232],
        [ 13.3780, -11.3342,  -1.6340,  -5.8129],


tensor([[-37.4548,  -4.9979, -38.1734,  21.0790],
        [ -7.5042, -11.4081,  15.1014, -15.4921],
        [-13.2805, -18.2103,  20.3735, -16.4195],
        [-21.0344,  -0.8398, -19.8697,   7.9036],
        [-27.0953,  -3.2919, -24.8420,  16.0321],
        [-16.0510,  14.5260, -14.9847,  -7.1889],
        [ -7.6024,   9.5168,  -6.6121,  -3.7436],
        [ 15.6473, -13.8200,  -0.3136,  -8.3744],
        [ 15.9119, -13.7696,  -2.2016,  -6.5936],
        [ 15.7878, -14.2462,  -3.8587,  -7.4348],
        [ 15.5832, -12.3922,  -2.2018,  -5.4431],
        [-12.6823,  12.8304, -12.3227,  -8.3356],
        [-24.3822,  -5.2493, -24.0789,  18.5419],
        [-20.6256,  -2.6258, -19.6752,   9.6820],
        [ 21.3195, -15.5363,  -6.1760,  -5.8941],
        [-15.3202,  20.3319,  -9.8092, -13.2570],
        [ -8.2142, -13.7470,  17.3146, -16.2218],
        [-22.0783,  -5.2416, -20.2516,  19.8079],
        [-20.9834,  -2.3906, -20.2984,  14.3284],
        [ 19.2757, -16.0950,  -3.6460,  -7.8323],


tensor([2, 1, 1, 1, 3, 0, 0, 2, 3, 0, 1, 2, 0, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1,
        3, 0, 3, 2, 1, 3, 1, 1])
tensor([[-11.6882,  14.3021,  -7.1628, -11.1174],
        [ 22.0614, -15.4889,  -8.0303,  -5.8477],
        [ -8.5015, -14.3792,  16.3325, -15.6032],
        [-30.0062,  -4.1965, -30.0383,  15.9770],
        [-24.3690,  -3.5553, -24.0731,  17.9306],
        [-18.2658,  11.7521, -19.6422,  -7.2275],
        [-11.0227,  15.3194,  -8.5826,  -9.3361],
        [-14.4163,  17.9536, -12.5500,  -9.1464],
        [-20.5966,  18.9222, -19.8509,  -9.2078],
        [-28.0287,  -3.9366, -26.6648,  14.6346],
        [-11.5398,  16.4294,  -8.7190,  -9.6352],
        [ 21.8550, -14.9825,  -4.5912,  -7.2510],
        [ -3.4888, -12.9348,  14.2394, -13.9046],
        [ 19.9038, -15.0360,  -4.0151,  -8.2598],
        [-12.9734,  18.9894, -10.1862, -11.0239],
        [-19.0664,  14.9618, -19.8864,  -8.2360],
        [ 18.1602, -11.4061,  -2.9058,  -5.8508],
        [ 23.9380, -16.1001,  -7.0021

Train Epoch: 5 [3168/24754 (13%)]	Loss: 0.000012
Train Epoch: 5 [6368/24754 (26%)]	Loss: 0.000815
Train Epoch: 5 [9568/24754 (39%)]	Loss: 0.000001
Train Epoch: 5 [12768/24754 (52%)]	Loss: 0.000000
Train Epoch: 5 [15968/24754 (64%)]	Loss: 0.000008
Train Epoch: 5 [19168/24754 (77%)]	Loss: 0.000000
Train Epoch: 5 [22368/24754 (90%)]	Loss: 0.000010
tensor([[ -7.6249,   7.8271,  -3.2753,  -6.2719],
        [-21.4058,  13.7168, -20.2056,  -9.9783],
        [  5.2041,  -5.5579,  -2.3359,  -3.6208],
        [  4.0725,  -4.5456,  -2.1360,  -3.3909],
        [  4.6111,  -2.7759,  -3.9512,  -2.1586],
        [ -6.9510,   6.0892,  -4.5938,  -4.9039],
        [-20.0623,  23.5632, -15.7466, -16.4489],
        [-13.3124, -24.2842,  15.8004, -25.3591],
        [-42.0690,  -6.8861, -41.9032,  20.7503],
        [-14.6661,  18.7089, -11.1643, -12.1585],
        [-35.8355,  -9.2403, -41.6985,  27.0459],
        [ -8.3228,   9.5231,  -5.0412,  -5.4792],
        [-37.3530,  -9.9803, -41.4682,  26.1592],
   

tensor([[ -3.1004, -13.0781,   3.6581, -14.3950],
        [ -6.5455,   7.6626,  -3.8801,  -5.3922],
        [-13.0828, -24.5818,  14.6785, -22.1739],
        [-12.1183,  15.3730,  -7.7205, -10.6785],
        [-20.6767,  14.9561, -20.0287,  -8.8587],
        [-18.7737,  22.9955, -14.6607, -14.0036],
        [-12.7409, -27.9439,  16.8398, -30.1510],
        [-15.4365,  19.7585, -11.9937, -12.0707],
        [  4.6901,  -5.7938,  -3.3943,  -4.2487],
        [-12.1553, -22.9112,  14.4642, -21.0766],
        [-11.6238,  14.8642,  -7.7942,  -9.4072],
        [  4.0781,  -7.0768,  -1.3410,  -5.4669],
        [-14.8725,  16.9773,  -8.7399, -15.4443],
        [-11.9705, -27.0838,  15.3700, -29.1330],
        [ -8.1783,  10.2109,  -5.6452,  -6.6633],
        [-42.9736, -10.8519, -46.3739,  28.7289],
        [ -2.0797,  -3.7055,   2.6293,  -4.3320],
        [-14.6245,  19.3017, -11.7655, -11.1589],
        [ -6.0198, -11.1098,   7.8444, -13.2743],
        [ -5.1107, -13.0623,   5.4742, -14.1294],


tensor([[ -6.8573,   8.4046,  -3.0067,  -6.1322],
        [-17.7530,  21.5502, -13.3530, -12.8906],
        [-46.1783, -11.9740, -49.6217,  21.3089],
        [-12.2158, -25.1830,  14.9000, -26.0300],
        [-12.1903, -22.8537,  13.9248, -23.7704],
        [ -6.6883, -13.7841,   7.7974, -13.4010],
        [-14.9786, -32.9630,  18.3255, -34.9332],
        [-40.6782,  -8.4814, -45.6797,  28.3437],
        [-11.5709, -24.0098,  16.5142, -24.6563],
        [-30.5712,  19.2799, -27.0415, -13.2679],
        [-10.7105, -26.4632,  11.1794, -28.7703],
        [ 13.2394, -11.0369,  -6.7612,  -6.7870],
        [-49.4562,  -9.9744, -52.6986,  25.1927],
        [-18.5217,  22.5610, -14.4854, -13.6962],
        [-10.1595, -29.7652,  14.0136, -32.2984],
        [-19.3153,  20.9659, -18.3959, -12.3754],
        [-12.7622,  14.1178,  -9.1042, -10.9764],
        [ -5.8567, -15.8289,   7.8280, -17.7170],
        [-13.3825,  15.8855, -12.9387,  -9.8152],
        [ 14.0646,  -7.5053,  -9.7639,  -5.5167],


tensor([[ -9.6627, -17.3503,  13.3344, -15.6660],
        [-12.2919,  14.7932,  -7.6394, -11.6083],
        [  6.7159,  -4.5728,  -5.3933,  -3.2039],
        [-31.1050,  -7.0166, -32.2777,  16.7423],
        [ -7.0433, -20.5319,   9.9979, -20.1569],
        [-25.3990,  18.7924, -21.9428, -11.7836],
        [-30.7519,  -6.7241, -32.2804,  17.7423],
        [  7.3524,  -6.2296,  -5.9848,  -4.7648],
        [-13.2200,  16.6119, -10.1593,  -9.0587],
        [-26.2705,  -5.8895, -27.8996,  17.1121],
        [ -6.2905, -18.4988,   7.7315, -22.8891],
        [-23.7733,  18.4973, -21.2744, -11.7354],
        [-32.8526,  -6.4424, -36.0221,  19.1083],
        [ -8.8524,  11.0767,  -3.8079, -10.0261],
        [-15.2730,  -3.1350, -16.9049,  10.4210],
        [ -8.1797, -18.7260,   9.8752, -19.9560],
        [-24.0503,  28.1949, -19.3578, -17.2069],
        [-10.5080, -19.2970,  14.8095, -19.3982],
        [-10.6472,   8.2605,  -8.4895,  -4.6194],
        [ -7.8176, -16.9783,  10.4405, -19.4901],


tensor([[  4.0548,  -3.8597,  -2.7725,  -2.8578],
        [  4.9183,  -5.1803,  -2.5432,  -3.8194],
        [ -8.0734,  10.0680,  -4.3966,  -8.4230],
        [-17.1579, -29.0987,  19.2101, -29.5671],
        [-44.7747,  -9.3172, -48.7750,  23.6606],
        [-15.9584,  18.3610, -12.4991, -11.1191],
        [-15.2969, -24.0740,  17.1874, -24.8368],
        [-12.3895, -25.9187,  15.8976, -26.6201],
        [ -9.5827, -21.6148,  11.1383, -22.7669],
        [-12.1650, -26.9421,  16.9152, -28.8769],
        [ 18.8016,  -8.2437, -14.5698,  -6.5548],
        [ 11.4732,  -9.9840,  -4.3030,  -5.4931],
        [  6.7895,  -2.6341,  -5.7427,  -2.5707],
        [  6.6398,  -7.5468,  -4.7729,  -5.8167],
        [ 13.9545, -11.0704,  -2.4297,  -7.2635],
        [ -4.8819,  -9.1222,   6.1462, -10.0310],
        [-12.0493,  14.6103,  -6.9643,  -9.0582],
        [  6.1871,  -5.9569,  -2.4632,  -4.0182],
        [-33.9124, -10.7057, -38.9292,  23.8239],
        [ 13.8412,  -6.3115, -12.2793,  -4.0981],


tensor([[ 11.4332,  -6.1801,  -7.5819,  -4.5801],
        [ -8.0383,  10.2830,  -4.8396,  -7.0775],
        [ 14.0595,  -5.1898, -11.7288,  -4.4058],
        [-36.1247,  -8.7846, -37.8323,  15.4157],
        [ -5.9794, -17.5927,   9.1954, -18.7819],
        [ 17.8925,  -8.9572, -14.4338,  -6.8478],
        [ -6.6776, -15.2267,   9.3677, -15.3053],
        [ -7.7192, -24.0560,  11.9999, -26.4032],
        [-14.2954, -29.0561,  19.2661, -33.3154],
        [  4.3114,  -3.2597,  -3.8260,  -2.3663],
        [-28.3302,  27.3602, -24.4658, -17.4100],
        [-38.8601, -10.9829, -41.9944,  18.1891],
        [ -6.3530,   7.6303,  -3.0792,  -7.5687],
        [ -9.0747,  12.9062,  -4.9873,  -8.2545],
        [ 13.3986,  -7.4464, -10.1631,  -5.3622],
        [ 13.8153,  -4.3377, -11.7375,  -5.1250],
        [ -7.0210, -13.2156,   6.3758, -16.5628],
        [-48.7833, -10.9821, -52.1399,  28.9129],
        [ -5.9837, -13.8031,   7.5203, -16.6843],
        [  8.3881,  -6.3286,  -6.0678,  -4.9069],


tensor([[ 11.3226,  -4.4954,  -8.8349,  -3.9753],
        [-41.9180,  -8.4515, -43.0775,  20.4674],
        [-31.6982,  -7.2503, -32.9220,  16.5915],
        [-11.7874, -22.4917,  13.9541, -25.1039],
        [  5.8822,  -5.5888,  -2.3520,  -3.5917],
        [-42.9491,  -8.0301, -43.7644,  20.8441],
        [-12.6082, -28.9000,  15.3282, -30.1387],
        [-14.8135, -31.9194,  18.5267, -32.3887],
        [-11.9005,  14.7545,  -7.3473, -12.0047],
        [-22.0539,  -3.1458, -23.0271,   9.5446],
        [  8.5734,  -4.3625,  -6.0219,  -3.7199],
        [-44.8837, -10.8058, -46.6811,  22.3868],
        [  8.7692,  -6.3296,  -5.6521,  -4.5972],
        [ 19.5791, -13.2611,  -9.4141,  -8.5097],
        [  9.3079,  -2.1657,  -8.3989,  -3.2342],
        [-11.4894,   7.7642,  -8.4404,  -5.2854],
        [  5.4868,  -5.2581,  -2.1095,  -3.8290],
        [-13.5257,  15.2602, -10.3932,  -9.5816],
        [  3.8013,  -4.0483,  -2.4774,  -2.6623],
        [ 11.0509,  -5.5071,  -7.2126,  -4.9552],


tensor([[-39.3626,  -8.7613, -41.8144,  22.0504],
        [-28.9974,  23.6804, -26.0939, -14.2863],
        [ -5.9113, -11.6212,   7.4437, -11.7153],
        [ -8.0298, -11.2694,  10.0925, -11.1270],
        [-24.9037,  22.9845, -21.3900, -15.0391],
        [-13.2068,  15.3268,  -9.2410, -10.0907],
        [-46.0714,  -9.4760, -50.7127,  30.1027],
        [ 11.4795,  -8.7012,  -9.6659,  -5.0016],
        [ -7.6786,   6.9362,  -4.3852,  -6.9265],
        [ -5.2577,  -8.3464,   6.0060, -10.4075],
        [-19.3656,  17.5386, -18.0492, -12.0869],
        [-11.8326, -25.5320,  15.1668, -26.9178],
        [-28.2149,  24.1435, -26.3971, -15.0978],
        [ -9.9968, -21.2663,  12.6283, -22.5104],
        [-26.4850, -10.3106, -33.4101,  25.3736],
        [ 10.9086,  -7.3819,  -7.7670,  -5.0288],
        [ -9.0745,  11.3291,  -5.1529,  -8.0340],
        [ -9.2682,  12.0789,  -6.4848,  -7.1658],
        [-41.7759, -10.6763, -44.2179,  21.6648],
        [-14.8002,  17.9280, -10.1504, -12.1858],


tensor([[-20.2633,  17.1402, -17.6115, -11.4882],
        [ -9.3568, -18.6562,  12.1012, -21.7710],
        [-12.5585, -22.5345,  15.9503, -23.8175],
        [ -8.3257, -17.8049,  12.2281, -19.9077],
        [-11.0258, -24.7546,  14.4433, -28.0310],
        [ -7.3448,   9.2882,  -3.6102,  -7.4417],
        [-15.9715,  18.7582, -13.8383, -13.4819],
        [-10.9069,  13.3453,  -8.4476,  -8.7994],
        [-43.9072,  -9.1132, -44.6366,  20.4807],
        [-38.0255,  -6.8918, -38.9318,  18.2952],
        [-14.7406,  17.8477,  -8.7940, -12.5615],
        [-21.0659,  -5.7000, -24.0926,  10.7906],
        [-27.4174,  -6.5364, -31.3258,  16.7348],
        [-42.0855, -10.3268, -46.8080,  21.7297],
        [ -8.7449,  11.6358,  -4.5409,  -8.0683],
        [ -6.5940, -18.1545,   9.3055, -18.2459],
        [-46.3170,  -7.9281, -47.4402,  25.5245],
        [-10.6708,  13.0302,  -7.4185,  -8.4575],
        [  9.9563,  -3.2262,  -8.9393,  -2.7656],
        [-12.0401,   4.6373,  -9.1666,  -4.4722],


tensor([[-41.2599, -10.4803, -45.8086,  28.2322],
        [ -6.2146,  -9.7629,   7.2411, -12.4083],
        [ -9.0978, -22.1831,  12.2877, -23.3650],
        [ -7.7925, -16.2832,   8.4485, -19.0438],
        [ -4.0744, -11.6163,   4.9534, -13.0035],
        [-35.4006,  -8.6953, -36.9574,  13.2102],
        [ 16.8778,  -5.0941, -14.4785,  -6.2055],
        [ -8.0964, -11.6245,   8.0398, -13.2674],
        [-11.4265, -17.2511,  13.3086, -17.6742],
        [-28.4283,  -7.7122, -32.2483,  18.1338],
        [ -8.1722,   5.7578,  -5.3443,  -3.2411],
        [  8.6635,  -6.0569,  -3.6612,  -5.0037],
        [ -0.8240,  -7.1100,   1.8987, -10.3253],
        [-37.2209,  -9.1845, -42.3942,  23.0813],
        [-22.9027,  25.4884, -18.2722, -17.1626],
        [  7.3154,  -3.0110,  -5.8215,  -2.7487],
        [  4.9534,  -5.6678,  -3.1603,  -3.4528],
        [ -8.0967, -17.0605,   9.3323, -20.6956],
        [-44.3086, -10.7460, -47.4773,  27.4457],
        [ -7.5764,   8.2015,  -4.5871,  -6.5162],


tensor([[-37.8334,  -8.6385, -38.9374,  18.3048],
        [-28.7846,  25.5024, -26.6015, -15.7595],
        [ -7.6816,   5.7962,  -4.8874,  -3.3341],
        [ -7.8607,   5.9827,  -5.4204,  -3.5741],
        [-12.5946,  15.4230,  -8.1453, -10.1877],
        [ -5.6837, -16.7322,   9.4834, -18.5930],
        [-18.9237,  13.2743, -17.5960,  -8.3273],
        [-37.4840,  -7.4955, -38.3172,  17.1767],
        [-24.3841,  18.6229, -22.0628, -12.4564],
        [-15.5317, -24.4244,  17.4626, -24.1783],
        [  5.6877,  -6.9499,  -2.1795,  -4.6629],
        [-42.6134,  -9.9164, -44.9815,  18.9889],
        [-16.1840, -31.5261,  19.1147, -32.9229],
        [-10.7963, -17.2718,  11.7712, -18.8330],
        [ 10.5049,  -8.7563,  -6.2260,  -5.2017],
        [-13.2436, -26.7858,  15.3973, -31.1236],
        [ -8.0618, -15.3602,   8.9351, -16.3251],
        [  5.9844,  -4.3616,  -4.0849,  -2.8766],
        [-12.5349,   5.2271,  -9.2715,  -4.1862],
        [-16.1723,  19.4326, -10.8562, -12.6072],


tensor([[-10.8516, -18.3661,  14.8049, -17.9159],
        [-13.8108, -25.5889,  15.9398, -24.1520],
        [-10.3237, -25.8171,  13.4379, -27.0680],
        [ -7.3569, -16.6167,   9.7674, -18.9441],
        [ -9.8082,  11.6249,  -7.7966,  -8.1775],
        [-15.4580,   6.7031, -17.5796,  -4.4317],
        [-46.0796,  -9.7158, -47.6163,  23.6814],
        [-36.4076,  -9.0844, -40.7980,  23.6217],
        [  9.4053,  -6.2502,  -6.8489,  -6.4526],
        [-26.9709,  -7.9627, -31.4381,  17.6023],
        [-22.0163,  19.9944, -20.5285, -12.8922],
        [-23.3440,  26.4623, -18.9602, -17.0293],
        [-29.5370,  -9.8788, -34.6528,  26.1728],
        [ 12.0759,  -4.5572, -10.9956,  -3.6177],
        [-17.8962,  20.3840, -13.8005, -13.2936],
        [ -9.1936,   3.3133,  -8.7347,  -2.3586],
        [ -4.4049, -15.5438,   6.9619, -17.6133],
        [-22.8703,  22.5110, -19.9588, -13.5550],
        [-45.7431,  -9.2564, -48.6134,  20.8264],
        [-13.6951,  16.0738,  -9.8292, -11.1656],


tensor([[-21.9599,  -4.9159, -26.6713,  19.9177],
        [  9.6541,  -3.5768,  -7.3047,  -3.2896],
        [-17.3823,  20.4918, -12.8398, -13.4987],
        [-24.1244,  26.2733, -20.2951, -14.9338],
        [-21.9899,  16.5500, -20.2737, -11.7997],
        [-19.8117, -37.4912,  23.1149, -37.0342],
        [-10.2854, -23.9623,  14.1671, -27.3769],
        [ 19.7874, -12.2060, -12.0883,  -8.3836],
        [-16.9097, -31.4648,  18.5982, -31.4183],
        [ 15.8318,  -9.8670, -10.2039,  -6.4842],
        [-28.2832,  -7.2649, -31.8248,  17.6516],
        [ -6.5314, -20.9763,   7.8493, -23.3290],
        [  5.4551,  -4.3219,  -3.4286,  -3.1323],
        [-36.4175,  -7.3247, -37.2582,  17.7566],
        [-41.6886, -10.0728, -47.2620,  25.8528],
        [-10.1166, -20.1449,  14.0218, -21.4108],
        [ -5.5469, -11.9666,   5.7494, -16.3929],
        [ 17.3156,  -8.7152, -13.2588,  -6.1790],
        [-25.1452,  -7.5806, -30.6735,  21.8276],
        [-14.3336,  15.7182, -10.5809, -10.3582],
